### ISSUE TITLE
Provide support for all cmap table formats

### ISSUE THREAD

**Issue by fdb** [opentypejs/opentype.js#105]
E.g. platformID = 1, encodingID = 0 as used in http://www.ivank.net/BRUSHSTP.ttf.

**Comment by Pomax** [comment]
I'd somewhat advocate not bothering with this - the format is so old nothing makes these fonts anymore (the format 0 cmap is horrendendously inadequate for anything but toy fonts =)

**Comment by bitinn** [comment]
Looks like Apple just decides to use platformID = 0 for their default system font, see #139

**Comment by Jolg42** [comment]
cmap 12 read support was just added with PR #207  😉

**Comment by fdb** [comment]
Any other important formats we should support?

**Comment by Jolg42** [comment]
@fdb 4 is limited to 16 bit (Unicode Plan 1) & 12 to 32 bit (All Unicode Plans) they follow the same specification & it looks like they're the most common cmap tables.

I decompiled some fonts with FontTools & found that format 6 is also common.
So maybe the next step will be reading format 6 but if nobody is having a problem now, maybe we can wait before implementing it 😉

**Comment by Pomax** [comment]
cmap 13 and 14 are high value for properly more modern fonts that need the many-to-one, and variation selection character mapping.

**Comment by Jolg42** [comment]
@Pomax Nice to know!
I think that CMAP 12 writing is the most important right now but one day maybe we will support every format ;)

But before that we will need to change how the cmap tables are handled, because right now if the cmap 12 is found the cmap 4 is not read (this is not a problem as 12 is a superset including 4) but we can't do that if we're adding more formats.
 
By the way are the 13 & 14 well implemented now?

**Comment by Pomax** [comment]
They're getting to.

I'm not sure why you'd skip 4 if 12 is found, though, but then I've not read the code in quite a while; keeping the UCS-2 and UCS-4 sets separate is generally a good idea, sometimes even with a cmap 0 for the 256 ANSI block, so the cmap parsing procedure is that you check which cmap subtables are available, then run through each of those to find your character index. The "does this character have an index according to this subtable" is a generally fast procedure, so you might "waste some time" looking in tables, but it will be negligible compared to the time necessary to render the glyph outline.

Also note that cmap 13 uses the exact same data structures and information coding as 12, except that the "start glyph" for a character range as used in 12 is simply considered "the only glyph" in 13, so if you have an implementation for 12 already, adding support for 13 (barring needing a rewrite on how characters are mapped through multiple cmap subtables of course) is virtually no extra work.

**Comment by Jolg42** [comment]
@Pomax The cmap 12 support was recently added by @Vildan & I think it was just easier to skip 4 if 12 was found. If not, it will need a rewrite. For now, it's easier & performance-wise faster, but not future-proof!

Thanks for the details though!
Personally, I'm already busy with a lot of other things so feel free to contribute if you need to 😉

**Comment by Pomax** [comment]
skipping 4 when 12 is found is a great way to not find characters that are definitely in the font, so filing an issue to make sure all sub tables are checked will be a good idea =)

as for contributing: I run an insane amount of projects already, so writing comments or just talking about how the opentype spec wants things done is a quick and easy job, reviewing code is a bit more work, *writing* code is more work than I have free time for at the moment =)

**Comment by fdb** [comment]
Hey @Pomax thanks for clearing that up. It sounds it'll be a good idea to keep all of them and do a lookup through them. Do you know if the spec says something about the order in which they should be looked up?

**Comment by Vildan** [comment]
Because there are only format 4 and 12 now, and 12 is superset of 4, there is no need to read format 4 if a font has format 12 in it. And because cmap tables placed in ascending order, we can find format 12 before format 4. @Pomax, do you have an example when we skip characters if read only format 12? I ran this test on 4000+ fonts and didn't find a single font where format 4 gives some extra characters versus format 12

**Comment by Pomax** [comment]
Rereading the spec, you're right; it quite literally says `"Please note, that the content of format 12 subtable, needs to be a super set of the content in the format 4 subtable. The format 4 subtable needs to be in the cmap table to enable backward compatibility needs."`. I'm curious if the OpenType spec revisions will remove this need for a cmap_4 in the future, but it does indeed fully justify not bothering with reading the subtable 4 format.

**Comment by brawer** [comment]
Here’s some [test cases](http://rawgit.com/unicode-org/text-rendering-tests/master/reports/OpenType.js.html#CMAP-1) for cmap subtables; see [README](https://github.com/unicode-org/text-rendering-tests/blob/master/README.md) for how to run the test suite.

**Comment by laoshu133** [comment]
We create a font subset online DEMO that compares some of the differences between opentype.js and fonttools subsets, may be helpful.

http://fonter.dancf.com/examples/subset/

**Comment by mooman219** [comment]
Technically by support format 12, you get format 13 for free right?

**Comment by jdimeo** [comment]
I have a TON of PDFs that use 14. Just throwing my vote in for this- I have no idea what it's all about :-)

**Comment by Connum** [comment]
We are meanwhile supporting format 14 (via #581) as well as format/encoding 0 for platform 1 (via #634), which the issue was originally about. The provided example `BRUSHSTP.ttf` will load fine with the current master.

If anyone could provide a font using format 13, that would be great.

**Comment by brawer** [comment]
> If anyone could provide a font using format 13, that would be great.

Added a [test case](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/OpenType.js.html#CMAP-4) using [this font](https://github.com/unicode-org/text-rendering-tests/raw/main/fonts/TestCMAP13.ttf).

**Comment by Connum** [comment]
Format 13 will be supported via #647, which will close this issue. As discussed before, it's not worth the time to support obscure formats that will probably never be encountered in the wild. Anyone providing a real font with an unsupported format is still welcome to open a new issue for that, of course!
