### ISSUE TITLE
Support for 'SVG ' table

### ISSUE THREAD

**Issue by davelab6** [opentypejs/opentype.js#106]
The `SVG` table has been added to the ISO OFF and Microsoft OpenType specification. It would be really great to support this in opentype.js :)

**Comment by felipesanches** [comment]
@davelab6, can you place a link to the appropriate specs here, please?

**Comment by moyogo** [comment]
@felipesanches the usual place for OT specs:
http://www.microsoft.com/typography/otspec/SVG.htm
