### ISSUE TITLE
Kozuka Mincho and Kozuka Gothic throw a ton of "unknown operator" errors

### ISSUE THREAD

**Issue by Pomax** [opentypejs/opentype.js#132]
Using Adobe's Kozuka fonts with OpenType.js results in a whole lot of errors about unknown operators. It looks like it's not decoding the CFF charstring properly...

These two fonts are not free, but come "for free" with any Adobe CC product like Illustrator and Photoshop (including the trial versions), so testing with these fonts should be pretty easy.

```
processing minchou
Glyph 125: unknown operator 0
Glyph 125: unknown operator 0
Glyph 125: unknown operator 0
...
Glyph 1164: unknown operator 0
Glyph 1164: unknown operator 0
Glyph 1164: unknown operator 0
Glyph 1170: unknown operator 16
Glyph 1170: unknown operator 0
Glyph 1178: unknown operator 0
Glyph 1185: unknown operator 0
...
Glyph 1313: unknown operator 0
Glyph 1317: unknown operator 0
Glyph 1322: unknown operator 1200247
Glyph 1326: unknown operator 0
Glyph 1326: unknown operator 0
...
Glyph 1543: unknown operator 0
Glyph 1543: unknown operator 0
Glyph 1543: unknown operator 0
Glyph 1547: unknown operator 12007
Glyph 1551: unknown operator 2
Glyph 1551: unknown operator 16
Glyph 1551: unknown operator 2
Glyph 1555: unknown operator 0
Glyph 1560: unknown operator 0
Glyph 1560: unknown operator 0
...
```

**Comment by miguelsousa** [comment]
Similar to #118

**Comment by miguelsousa** [comment]
@Pomax perhaps you could expand `cff.js` as it was done in #91 and #89.

**Comment by Pomax** [comment]
I don't see a counter comment on #118, but they are a really big deal: the glyphs I'm trying to render look positively destroyed compared to what they *should* look like =)

I am not going to work on the code unless I absolutely have to (I've spent so much time working on font parsers in the past that I really don't like writing the same code yet again, it literally makes me a very irritable and angry person, so I try not to) but I'll be happy to help you find out where the problem is and if it's a simple fix, write that up. Just please don't rely on me actually doing that since I already work on a *lot* of projects. I might do this tonight, or I might never come back to it.

**Comment by Pomax** [comment]
I would recommend simply taking an already proven correct parser for CFF, though, such as the one used by PDF.js over at https://github.com/mozilla/pdf.js/blob/bf20334bea5433915f133e590e223ca8ff2bde32/src/core/fonts.js#L5883

**Comment by fdb** [comment]
Thanks, will take a look at it.

**Comment by miguelsousa** [comment]
What's happening is that the parser is not taking into account that these are CID-keyed fonts and is stumbling into all the subroutines. The advanced widths are also messed up. @tshinnic addressed these things with PR #92. I did a bit of testing and these are the before and after screenshots using Kozuka Mincho:
**before**
![kozmin_before](https://cloud.githubusercontent.com/assets/2119742/8391019/d874b798-1c64-11e5-8a8b-b66afbacd303.png)
**after**
![kozmin_after](https://cloud.githubusercontent.com/assets/2119742/8391020/ec921f0e-1c64-11e5-9944-e0426dd8e7ee.png)

@fdb perhaps it's worth merging #92 even though Tom mentioned that it's incomplete. The improvements to CID-keyed font parsing are quite significant there.

**Comment by fdb** [comment]
Yeah I agree. I just need to find to go through it.

**Comment by Pomax** [comment]
sweet!

**Comment by Connum** [comment]
Support for CID-keyed fonts was added via #284 long ago, I just tested the Kozuka fonts and they appear to render fine. I'll close this issue, please reopen should there be any further issues.
