### ISSUE TITLE
Using web workers

### ISSUE THREAD

**Issue by focomoso** [opentypejs/opentype.js#174]
I'm trying to include opentype support into another open project (openJScad) that does just about everything in web workers. Because of this, opentype.load() defaults to loadFromFile (because there's no window). I've worked around this by just forcing load() to use loadFromUrl(), but I'm now getting a cross origin error when trying to load the file from my server.

"XMLHttpRequest cannot load . Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource."

Is there any way to get around this?

Also, is trying to use opentypejs in a web worker just futile? Should I look for another solution altogether?

Thanks

**Comment by davelab6** [comment]
I believe the @byte-foundry team may have some insight into this :)

**Comment by fdb** [comment]
Technically there is no reason OpenType.js couldn't work in a web worker. 

I would start to see if `opentype.parseBuffer` works in a web worker, giving the arraybuffer data you would get normally back from the AJAX request.

**Comment by fdb** [comment]
Here is some completely untested example code:
```
importScripts('/lib/opentype.min.js');
var onmessage = function(e) {
    // Asume e.data.fontURL contains the URL of the font to load.
    var request = new XMLHttpRequest();
    request.open('get', e.data.fontURL, true);
    request.responseType = 'arraybuffer';
    request.onload = function() {
        if (request.status !== 200) {
            return postMessage('Font could not be loaded: ' + request.statusText);
        }
        var font = opentype.parseBuffer(request.response);
        return postMessage(null, font);
    };
};
```

**Comment by danmarshall** [comment]
I am using opentype.js in a web worker and it works just fine. One request I have is being able to load synchronously when in a worker. Perhaps [loadFromUrl](https://github.com/nodebox/opentype.js/blob/master/dist/opentype.js#L1975) can change ```true``` to ```false``` when there is no callback?

**Comment by davelab6** [comment]
Good news @danmarshall :) cc @graphicore

**Comment by danmarshall** [comment]
Actually, let me qualify that - I did need to trick opentype.js by adding:
```
var window = {};
``` 
It would be nice to not need to do this.

Here's how I detect the 3 types of environments in Maker.js :
```
    function detectEnvironment() {
        if (('global' in this) && ('process' in this)) {
            return environmentTypes.NodeJs;
        }

        if (('window' in this) && ('document' in this)) {
            return environmentTypes.BrowserUI;
        }

        if (('WorkerGlobalScope' in this) && ('self' in this)) {
            return environmentTypes.WebWorker;
        }

        return environmentTypes.Unknown;
    }
```

**Comment by fdb** [comment]
Ah that makes sense, since `window` is not defined in a web worker. 

We just want to distinguish between node and the browser, though. I tried this through checking for `process` but apparently browserify defines it. I've seen `typeof self === object` as a check, would that make sense?

**Comment by danmarshall** [comment]
That's why I look for both 'global' and 'process'

**Comment by hyvyys** [comment]
Actually `self.window = {};` did the trick for me as I'm using a build step (Webpack), so maybe because of that `var window = {};` didn't work for me.
