### ISSUE TITLE
Macintosh Unicode cmap (Platform ID = 0, Encoding ID = 3, Format = 4) support.

### ISSUE THREAD

**Issue by HinTak** [opentypejs/opentype.js#185]
I have a font which shows

```
TypeError: font.tables.cmap is null
```

on https://nodebox.github.io/opentype.js/font-inspector.html

In reality it is just a perfectly valid font with a Macintosh Unicode 2.0 cmap (Platform ID = 0, Encoding ID = 3, Format = 4) . And to be honest, for small fonts supporting european languages only, or even English glyphs only, they are equivalent.

**Comment by Connum** [comment]
Platform ID = 0, Encoding ID = 3, Format = 4 should be supported, could you provide the font in question?

**Comment by Connum** [comment]
Should definitely wrk with the current master (probably even earlier). Closing now, reopen or new issue if there are any other issues regarding cmap.
