### ISSUE TITLE
Alternative to opentype.js

### ISSUE THREAD

**Issue by photopea** [opentypejs/opentype.js#214]
Hi guys,

I have made my own parser and renderer [Typr.js](https://github.com/photopea/Typr.js). There is a [live demo](https://photopea.github.io/Typr.js/), where you can test your files. It is much smaller than opentype.js, but it can not encode files yet. It also supports some old file structures, for which opentype thorows errors. 

Maybe somebody would be interested in using it.  I have reported several issues regarding opentype.js in the past. You can look into the source of Typr.js to get an idea how to fix those issues.

**Comment by Jolg42** [comment]
Hi!

Nice :) I just added it to the [awesome-typography list](https://github.com/Jolg42/awesome-typography) (You can check this list for OpenType related libraries!).

If you want to check other alternatives to OpenType.js:
- https://github.com/devongovett/fontkit An advanced font engine for Node and the browser 
- https://github.com/bramstein/opentype An OpenType, TrueType, WOFF, and WOFF2 parser in JavaScript

Both are OpenType parsers (not writers).

I searched for your issues, but maybe you used another account for them (I can't find any)?

By the way if you have a .zip with fonts working / not working it would be helpful for testing! 😉

**Comment by fdb** [comment]
Hi @photopea, always good to see some alternative implementations! As @Jolg42 mentioned, there are some other high-quality implementations as well. I'll look at your implementation to see if there are any speed gains we can port over to OpenType.js as well.

If there are specific issues you'd like to see solved, please take them up with me (again). I've been completing my PhD in the last year(s) so OpenType.js was not always my nr 1 priority 😉

**Comment by photopea** [comment]
The most important problem with this issue, I was waiting more than a year, but nobody fixed it.  https://github.com/nodebox/opentype.js/issues/117 
Here you can see the same 100 glyphs rendered with opentype and Typr
![glyphs](https://cloud.githubusercontent.com/assets/15955558/17394943/035e4dec-5a2c-11e6-9bac-399aa739b199.png)

**Comment by photopea** [comment]
I was testin Typr.js with fontsquirrel fonts, which I accessed through their API: https://www.fontsquirrel.com/blog/2010/12/the-font-squirrel-api

**Comment by fdb** [comment]
Looking at that issue, could you pinpoint what your parser is doing differently? I'd love to fix this.

Thanks for the link to the fontsquirrel API. Didn't know about that one.

**Comment by photopea** [comment]
When there  is a CFF operator 14 (endchar) and stack length is 4, the "seac" (standard encoding accented character) command should be performed.  Opentype does nothing. See http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5177.Type2.pdf   page 35.

**Comment by fdb** [comment]
Thanks! I saw that was an issue with e.g. character index 202, which has the code `[98, 146, 154, 236, 247, 89, 14]` which sets up a stack with five numbers but then only does endchar. I was scratching my head on what that should do.

**Comment by Jolg42** [comment]
I just did a dump from the API, all fonts are available here https://github.com/Jolg42/FontSquirrel-Fonts

**Comment by photopea** [comment]
Nice :) but I think it will be outdated like tomorrow :D

**Comment by Jolg42** [comment]
Maybe…! But I don't think that the fonts are updated on regular basis. 
They add more new fonts than they update the old ones no?
Having a dump is just easier for testing (even if outdated).

**Comment by behdad** [comment]
> Thanks! I saw that was an issue with e.g. character index 202, which has the code [98, 146, 154, 236, 247, 89, 14] which sets up a stack with five numbers but then only does endchar. I was scratching my head on what that should do.

What was the solution that worked?  Early termination?

**Comment by fdb** [comment]
@behdad As @photopea mentioned, it should be interpreted as `seac`. We don't have code for this, I'll look into this.

**Comment by photopea** [comment]
Can you please also make sure, that you can render the glyph 190 in this font? I am having problems with it.

**Comment by ivarref** [comment]
Hi. 

I wrote [opentype.clj](https://github.com/ivarref/opentype.clj), a small wrapper for a subset of `opentype.js`. It runs on the Java Virtual Machine (JVM) and should be easy to interface using the [Clojure programming language](https://clojure.org/). Hope it's of good use to someone!

**Comment by Jolg42** [comment]
@photopea I just wanted to try it again :)
By the way, I don't remember exactly but when you created Typr.js it was partly because of an issue with the parsing of some glyphs I think. Do you know if this issue was fixed in OpenType.js?

**Comment by photopea** [comment]
@Jolg42 Yes, I did it because some issues were not fixed. It seemed to me like the author made opentype.js just for fun and did not plan to do updates.

I am the kind of programmer that prefers writing his own code instead of deciphering foreign code :D If I find a bug in Typr.js now, I can fix it right away myself. I made it because I actually need it in practice at www.Photopea.com . It is used by thousands of people every day and bugs have been found and fixed very quickly. In general, I trust Typr.js much more than opentype.js now . It is much more advanced, e.g. it even supports Color Fonts :) https://blog.photopea.com/color-fonts-in-photopea.html

**Comment by Connum** [comment]
The issue discussed above was fixed via #633. Closing.

**Comment by CNV1018** [comment]
hi, can I check if it supports TTC file? can it display all characters in TTC files? Currently, I'm using opentype.js. It works well with TTF and OTF, but it doesn't support TTC file. I'm currently looking for other alternatives.

**Comment by photopea** [comment]
Yes, Typr.js supports TTC files, I have updated the README: https://github.com/photopea/Typr.js

**Comment by CNV1018** [comment]
That's great!! I'm working on a .NET Core project with React for the front end. Can this tool be implemented into the project?
