### ISSUE TITLE
Unable to write GSUB lookup type 6 tables.

### ISSUE THREAD

**Issue by shabeernotion** [opentypejs/opentype.js#309]
## Expected Behavior
I have loaded **Ribeye-Marrow-regular.ttf**  font and trying to font.toArrayBuffer() on Aws

## Current Behavior
It throws following error:
Unable to write GSUB lookup type 6 tables.

**Comment by Jolg42** [comment]
Hi @shabeernotion 

So you could check https://github.com/nodebox/opentype.js/blob/master/src/tables/gsub.js
Reading of all GSUB types 1,2,3,4,5,6,7,8 are supported but only types 1,3,4 for writing.

Feel free to contribute and add the type 4 if you need it 😉

**Comment by shabeernotion** [comment]
May I know how to add type 2 and type 6?

**Comment by Jolg42** [comment]
So for adding the support for these 2 types you'll need to check how the reading part was done and  read the [OpenType specification](https://www.microsoft.com/typography/OTSPEC/gsub.htm) to understand how it works.
After that write your code and make sure it works well (reading / writing).

It's easier as the reading part is implemented but still need to be done 😉

**Comment by shabeernotion** [comment]
Should I implement in order to parse? Are there any other way that I can parse without doing it?

**Comment by Jolg42** [comment]
So parsing is already implemented actually!

**Comment by shabeernotion** [comment]
Yeah but actually this error throws on toArrayBuffer().

**Comment by Jolg42** [comment]
Yes indeed, so what's happening is that toArrayBuffer() is trying to convert the GSUB type 6 that was read when loading the font and it can't because it's not implemented.
Basically opening is working but when doing toArrayBuffer() you ask to convert the data back to a font format and it can't.

**Comment by Connum** [comment]
I've got writing for GSUB type 6 format 1 and 3 working so far:
https://github.com/Connum/opentype.js/tree/add-lookup-type-6
Testing and feedback is encouraged and would be great to have before creating a PR.
