### ISSUE TITLE
charToGlyphIndex() in encoding.js never returns null

### ISSUE THREAD

**Issue by debussy2k** [opentypejs/opentype.js#330]
So the hasChar() always returns true if this.encoding is an object of CmapEncoding.

```javascript
// font.js
Font.prototype.hasChar = function(c) {
    return this.encoding.charToGlyphIndex(c) !== null;
};
```

Below code, this.cmap.glyphIndexMap[c.charCodeAt(0)] never returns null.  Maybe the caller of charToGlyphIndex() except hasChar() want to receive 0(zero) for using it as index value if there were no mapping glyph.
```javascript
// encoding.js
CmapEncoding.prototype.charToGlyphIndex = function(c) {
    return this.cmap.glyphIndexMap[c.charCodeAt(0)] || 0;
};
```

**Comment by fpirsch** [comment]
Hi,
0 is the standard code for the `.notdef`glyph, to be displayed as a fallback.

**Comment by debussy2k** [comment]
@fpirsch you are definitely right. 
Because charToGlypnIndex() do not return null in any case, hasChar() will return true always.

```javascript
// font.js
Font.prototype.hasChar = function(c) {
    return this.encoding.charToGlyphIndex(c) !== 0;  // instead of !== null
};
```

**Comment by fpirsch** [comment]
suggestion:
`// font.js
Font.prototype.hasChar = function(c) {
    return this.encoding.charToGlyphIndex(c) > 0;  // checks both 0 and null
};`

**Comment by Jolg42** [comment]
@debussy2k Indeed...! @fpirsch Your solution looks good, should we add this in a next patch or minor version?

**Comment by tomvdbussche** [comment]
Are there still plans to implement this fix? This bug caused a lot of confusion until I found out about this issue.

**Comment by Connum** [comment]
> Are there still plans to implement this fix? This bug caused a lot of confusion until I found out about this issue.

It took only 5 years, but I just opened PR #632 😉
