### ISSUE TITLE
Integrate variablefont.js?

### ISSUE THREAD

**Issue by davelab6** [opentypejs/opentype.js#340]
I am curious if this project would take variable fonts support as a PR?

This is a sister issue for https://github.com/Monotype/variableFont.js/issues/5

**Comment by Jolg42** [comment]
Hi @davelab6 

It should be in the scope of this project! I didn't know variableFont.js until know but will review the PR if somebody submits it.

I remember merging this PR https://github.com/nodebox/opentype.js/pull/313 from @taylorb-monotype I guess it was related to that project.

Just something to consider, if some unit tests could be added with it it would be perfect!

**Comment by taylorb-monotype** [comment]
We created variableFont.js as a sort of class extension to opentype.js for a couple reasons.
1) so as to no balloon the size of opentype.js as we add more variable font specific things
2) allow very specific variable font features to be developed without disturbing opentype.js
(maybe that's one reason)

So, for example, any work to parse the HVAR table should and would be done in opentype.js and we would like to contribute that eventually (but it's complicated and have not had a chance to work on it). Then in variableFont.js you could use that information to do a spacing/tracking axis. 

If people think it makes sense for it all to be in opentype.js, that's fine. If variableFont.js does not grow beyond its current state, then it should certainly be merged back. At the moment it is simply a very simple extension. But as we and others add (hopefully) more advanced and more variable font specific features, it might make sense to have it be a separate class extension. 

I am not a JavaScript expert in any sense so I leave it to more knowledgeable people to recommend what makes sense for all users.

**Comment by davelab6** [comment]
Thanks for the detailed explanation Bob! That all makes sense to me :D

@Jolg42 are you concerned about the file size impact? 

For me I think the more 'swiss army knife' or 'batteries included' that opentype.js is, the better - however I can see that being able to "subset" the library through a modular code architecture could be very useful.

**Comment by Jolg42** [comment]
I think that more contributors/ions on OpenType.js is always better! (OpenType.js is still young, so more contributions could have a domino effect 😄)

About the file size not really, and I guess we could (in a far future!) build different versions of OpenType.js like a core and a full version.

But like @taylorb-monotype code about variable fonts needs to be isolated so it will be easier to maintain / contribute but it could be done within this repository.

**Comment by Connum** [comment]
@davelab6 @taylorb-monotype are you still interested in contributing a PR?

**Comment by Connum** [comment]
Closing as we now have an own implementation for variable font rendering (#699).
