### ISSUE TITLE
Question: is it possible for this library to get the bounding rect of each character in existing HTML tag?

### ISSUE THREAD

**Issue by kuyeduwu** [opentypejs/opentype.js#351]
Just for curiosity, say I have an HTML document with many <p> elements, and there are many words in each <p> element, is it possible to get the bounding rect of each character?

**Comment by axkibe** [comment]
I tried to this, and the answer is no.. You never know for sure what the font engine of the browser is doing, what font it is actually rendering with, what kind of optimizations it does, if ligatures or not etc.

If you want bounding rects, you either have to split you HTML in lots <span></span> tags around each letter, which will make the browser very slow and will also break up ligatures.. or you'll have to draw the text yourself in a canvas (this is what I resorted to) ... which has obvious problems with accessibility tough.

**Comment by kuyeduwu** [comment]
@axkibe, thx for the information, I figured out a way to get the bounding box by surround each character with a `<span>` tag, the performance is acceptable as long as I only process some part of the text in the document.

**Comment by axkibe** [comment]
Not that inserting <span> might change the content. At least the last I tried this approach ligatures ("AV" for example where the V is moved left into the A) were split apart by most browser rendering engines if they aren't within the same <span>
