### ISSUE TITLE
Parsing on node.js, rendering in browser

### ISSUE THREAD

**Issue by adriaanmeuris** [opentypejs/opentype.js#356]
## Expected Behavior
Feature request / help needed: we'd like to parse fonts on the server side (Node.JS) and only render the parsed font in the client (Browser).

## Current Behavior

The server part is a REST api endpoint which returns a JSON object containing all font information - basically the result of the opentype.js font instance.  This enables us to do validation (font support) and caching the results of each parsed font.
Output looks like this:
```
{
    "supported": true,
    "glyphs": {
        "glyphs": {
            "0": {
                "index": 0,
                "name": ".notdef",
                "unicodes": [],
                "advanceWidth": 748,
                "leftSideBearing": 67
            },
            ...
        },
        ...
     },
     ...
}
```
**Goal**: using the returned object in the client so we can skip parsing an `ArrayBuffer` on the client - to improve performance and reducing file size on the client.

## Possible Solution

**Idea**: to create an `opentype.js` instance in the client with an object as source.
Other ideas to get this working would be greatly appreciated.

## Your Environment

* Version used: 0.10.0
* Font used: all
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): All

**Comment by Jolg42** [comment]
Hi @adriaanmeuris 

Indeed it's not possible to do that at the moment.

Just an idea and maybe not working for your project but if you need the best performance why not using the font as a webfont directly? You could inject dynamically the font like this https://googlechrome.github.io/samples/font-face-set/ maybe.

**Comment by adriaanmeuris** [comment]
Thanks for your fast response @Jolg42. We're going with `opentype.js` since it offers access to path data and single glyphs, which allows us to render them on every path possible.

Do you think this might be possible by constructing a new opentype.js instance based on the parsed output from the API?
```js
var font = new opentype.Font({
  // insert properties retrieved from API like e.g. `glyphs`
});
```

Or would this cause us to lose data like `kerning` for example?

**Comment by Jolg42** [comment]
So the JSON object can't be used as the input because `font` is a complex object / instance with getters and setters attached for example.

The best way to do it would be to implement a `fromJSON` and `toJSON` methods.

Examples I have in mind:
https://github.com/paperjs/paper.js/blob/a61e83edf2ed1870bd41bad135f4f6fc85b0f628/src/core/Base.js#L535
https://github.com/parse-community/Parse-SDK-JS/blob/db59b63bcc37abf914a8b4fb261354e8aa6cdcc4/src/ParseFile.js#L206

I guess you could try to implement only the parts that you'll need `fromJSON` and `toJSON`

**Comment by adriaanmeuris** [comment]
Great - let me try that and get back to you.

**Comment by adriaanmeuris** [comment]
closing this as we've managed to parse this the way suggested. Thanks!

**Comment by Jolg42** [comment]
@adriaanmeuris Just curious, could you share an example of what you did here?

It could help other people in the future I guess 😉

**Comment by adriaanmeuris** [comment]
Since we're doing custom rendering on the client, we've used opentype to parse the font on the server side, returning a plain object that's consumed on the client (were we don't use opentype).

```js
import { parse } from 'opentype.js';
import forEach from 'lodash/forEach';

class OpentypeParser {
  constructor(buffer) {
    // Parse the font using opentype
    this.font = parse(buffer);
    
    // Loop over glyps
    this.glyphs = [];
    forEach(this.font.glyphs.glyphs, (g) => {
      this.glyphs.push({
        index: g.index,
        advanceWidth: g.advanceWidth,
        ...
      });
    })
  }

  toJSON() {
    return {
      glyphs: this.glyphs,
    };
  }
}
```

This class allows us to parse a font using opentype as a plain object (pseudo code)
```js
const buffer = fs.readFileSync('arial.ttf');
const obj = new OpentypeParser(buffer).toJSON();
console.log(obj); // Plain object to send as response to the client
```

This object can be used on the client as you wish, assuming you don't want to import the entire library there.

**Comment by Jolg42** [comment]
Great! Thanks 😉
