### ISSUE TITLE
`descender` is assumed to be negative, but zero should be allowed

### ISSUE THREAD

**Issue by skreborn** [opentypejs/opentype.js#357]
## Expected Behavior
The Material Icons font to be usable with `new Font({ ... })`.

## Current Behavior
The font can not be used, because the constructor throws an error:

```text
Uncaught (in promise) When creating a new Font object, descender is required.
```

## Possible Solution
The bug occurs because `Font` [expects](https://github.com/nodebox/opentype.js/blob/master/src/font.js#L60-L61) `descender` to be non-zero, while it is a valid value. A simple fix would be to change the checks as follows:

```javascript
checkArgument(typeof options.descender === 'number', 'When creating a new Font object, descender is required.');
checkArgument(options.descender <= 0, 'Descender should be negative or zero (e.g. -512).');
```

Although highly unlikely, I suppose it would also be correct to do the same with `ascender`:

```javascript
checkArgument(typeof options.ascender === 'number', 'When creating a new Font object, ascender is required.');
```

## Steps to Reproduce (for bugs)
```javascript
const opentype = require('opentype.js');

fetch('material-icons.otf')
  .then(response => response.arrayBuffer())
  .then(buffer => {
    const font = opentype.parse(buffer);

    new opentype.Font({
      familyName: 'Material Icons',
      styleName: font.names.fontSubfamily.en,
      unitsPerEm: font.unitsPerEm,
      ascender: font.ascender,
      // While `parse` correctly uses zero as a value, `Font` won't accept it
      descender: font.descender,
      glyphs: []
    })
  });
```

## Context
The font is read correctly in the playground and the inspector displays its `descender` to be zero, as expected, but the library version doesn't produce the same results, unfortunately.

## Your Environment
* Version used: 0.8.0
* Font used: Material Icons

**Comment by Connum** [comment]
This was already fixed some time ago via #422
