### ISSUE TITLE
Error: Unsupported OpenType signature <!DO

### ISSUE THREAD

**Issue by kaldrenon** [opentypejs/opentype.js#360]
```
Error: Unsupported OpenType signature <!DO
    at parseBuffer (opentype.js?6770:204)
    at eval (opentype.js?6770:378)
    at XMLHttpRequest.request.onload (opentype.js?6770:71)
```
## Expected Behavior
Font loaded from file.

## Current Behavior
Loading a font using https://github.com/shrhdk/text-to-svg and seeing this error from OpenType.js -- very unfamiliar with font formats so not able to infer much from the error message except that perhaps the font file is formatted in a non-standard way? Only relevant search result in Google was #278 but the error message is a little different.

Font fails to load.

## Possible Solution
I recognize that it's possibly the font file that's causing this issue but wanted to request input here in case this is an issue anyone recognizes.

## Steps to Reproduce (for bugs)
Not sure I can provide this, the font in question is proprietary and licensed.

## Your Environment

* Version used: 0.7.3
* Font used: Avenir
* Browser Name and version: Chrome 69
* Operating System and version (desktop or mobile): OSX High Sierra
* Link to your project: not public

**Comment by Jolg42** [comment]
Hi!

The `<!DO` reminds me of the DOCTYPE declaration for HTML files, could you make sure your font file is either in the OpenType .otf or TrueType .ttf format?

**Comment by kaldrenon** [comment]
Thanks @Jolg42 -- I found my problem, and it was actually a routing issue on the assets in my project, so OpenType was trying to load my site's 404 page as a font. That <!DO was in fact the top of that page's markup. Whoops!

Closing issue. Thanks.

**Comment by CubeOfCheese** [comment]
Hello, I am getting the same error, but I am definitely not loading an html page instead of an otf font, so I do not think the <!DO is the first part of the file being loaded. I am working in React with p5.js using p5-react-wrapper.
![Screen Shot 2019-06-13 at 11 35 05 AM](https://user-images.githubusercontent.com/16740469/59458683-d1da4480-8dcf-11e9-83fb-541c25c9823b.png)
![Screen Shot 2019-06-13 at 11 35 45 AM](https://user-images.githubusercontent.com/16740469/59458685-d1da4480-8dcf-11e9-8c7b-102b3842f8d0.png)
![Screen Shot 2019-06-13 at 11 36 10 AM](https://user-images.githubusercontent.com/16740469/59458687-d272db00-8dcf-11e9-9c54-84afc077579d.png)
![Screen Shot 2019-06-13 at 11 37 32 AM](https://user-images.githubusercontent.com/16740469/59458688-d272db00-8dcf-11e9-992a-93c761281f2b.png)

**Comment by Jolg42** [comment]
@CubeOfCheese What's happening is actually the same ie:

"<!DO" is for "DOCTYPE" the first tag in an HTML file, this mean that you're trying to open an HTML file. I guess it's a 404 page or something like this ;)

Check the path to your .otf file and try again. I also suggest opening the Console at the Network tab to see what's happening.

**Comment by CubeOfCheese** [comment]
Okay thank you, I see in the network tab that it is returning the index.html page for React, but I do not understand why.

**Comment by Jolg42** [comment]
Usually the best is to have assets in something like a `public` folder.

Maybe this could help https://facebook.github.io/create-react-app/docs/using-the-public-folder

**Comment by CubeOfCheese** [comment]
Moving the font file into the public folder and changing the filepath to point there still did not work. I am still receiving index.html as the response.

**Comment by Jolg42** [comment]
Not sure about that, but you could try to call the font with something like this:
"%PUBLIC_URL%/yourfont.otf"	(found this here https://medium.com/@jenniferdobak/the-public-folder-and-favicons-in-create-react-app-8dc2cc1d492b)

**Comment by katOstrynska** [comment]
Hello, I've got the same problem; I am using VueJS (version 3.11.0) and request font on click event.

`const opentype = require('opentype.js');
 opentype.load('@/assets/fonts/Inconsolata/Inconsolata-Regular.ttf', function(err, font) {
      if (err) {
          console.log('error with font')
          console.log(err)
      } else {
          console.log('success!')
      }
})`

My network tab:
![network](https://user-images.githubusercontent.com/32193007/72446999-da0ac000-37b4-11ea-85ab-d32d6bef0510.png)
![network_js](https://user-images.githubusercontent.com/32193007/72447007-dc6d1a00-37b4-11ea-8925-3f973b7dc5c4.png)
I am sure that I have js enabled in my browser.

**Comment by peilingjiang** [comment]
The thread has been silent for a long time but I just want to drop a word here in case anyone else get this problem in the future. I worked with p5 and React and got this problem. I was able to resolve it by import the file into the code and load it from there:

```js
import Roboto from './font/Roboto-Black.ttf'

// ...

p.setup = () => {
  p.loadFont(Roboto, font => {
    console.log('Success!')
  })
}
```

**Comment by monkeySalater** [comment]
Hi, I've been trying to solve this error but nothing from here works.

I have posted new issue with description of my problem.
If you possibly know  the solution or looking for one, please, visit:

https://github.com/opentypejs/opentype.js/issues/462

THANKSSS!!!

**Comment by mnearents** [comment]
I am also getting this error except instead fo <!DO it says "Unsupported OpenType signature wOF2". The interesting thing is the font works fine when I'm running a local web server. But when I try to load the font via URL, I get this error. The font file is .ttf.

**Comment by asadullahjan** [comment]
I resolved mine by changing the .ttf to .otf

**Comment by Sanghyun0505** [comment]
The same error occurred to me, but I couldn't solve it. help me plzzz😭

```
import { CallbackType, OptionType } from "./type";
import opentype from "opentype.js";
import wrap from "word-wrap";

export const titleMaker = (options: OptionType, callback: CallbackType) => {
  const path = `../../fonts/${options.font || "GangwonEduPower"}.otf`;

  opentype
    .load(path)
    .then((font) => {
      const wrapText = (text: string, width: number): string[] => {
        const wrappedText = wrap(text, { width }).split("\n");
        if (wrappedText.length > 3) return wrapText(text, width + 1);
        else return wrappedText;
      };

      const textArray = wrapText(options.title, 6);

      const maxWidth = font.getAdvanceWidth(
        textArray.reduce((a, b) => (a.length <= b.length ? b : a)),
        100
      );

      const result = textArray
        .map((item, index) => {
          const xPos = () => {
            if (options.alignLeft || false) return 0;
            else return (maxWidth - font.getAdvanceWidth(item, 100)) / 2;
          };

          const path = font.getPath(item, xPos(), 100 * (index + 1), 100);
          return path.toSVG(0);
        })
        .join("");

      const svg = [
        '<?xml version="1.0"?><svg',
        'xmlns="http://www.w3.org/2000/svg"',
        'xmlns:xlink="http://www.w3.org/1999/xlink"',
        `fill="${options.color || "white"}" width="${maxWidth}" height="${
          textArray.length * 110
        }"><g>${result}</g></svg>`,
      ].join(" ");

      callback(svg);
    })
    .catch((err) => {
      console.log(err);
    });
};

```
