### ISSUE TITLE
Document how to add a ligature

### ISSUE THREAD

**Issue by ExplodingCabbage** [opentypejs/opentype.js#363]
The docs in the README currently provide a straightforward copy-paste-ready example of how to replace a particular glyph in a font with an alternative glyph. I would like to add a ligature to a font, but the docs do not have a similarly idiot-friendly example of how to do so.

Could somebody add such an example to the documentation? There is [a test](https://github.com/opentypejs/opentype.js/blob/4e0bb99d4471369a68b53dd4ef2db9eca73a5b04/test/tables/gsub.js#L107-L130) that involves ligatures, but it's kind terrifying and incomprehensible and I am not clever enough to understand it.

**Comment by solomancode** [comment]
Hi @ExplodingCabbage ,

Check this test file **/test/font.js**. There is a straight forward example on how to add a ligature to a font. 

https://github.com/opentypejs/opentype.js/blob/637856c9f5a36f67ffd2afdc53cc46dff46c0f3e/test/font.js#L4-L47

If you require further assistance, please leave a comment.

**Comment by ExplodingCabbage** [comment]
Thanks for this and sorry for my slow reply. That example was good enough for my purposes.
