### ISSUE TITLE
Format for font's created time stamp

### ISSUE THREAD

**Issue by orklann** [opentypejs/opentype.js#368]
It seems there is no specific documentation for this created timestamp, all I know it's a `Number`.

https://github.com/opentypejs/opentype.js/blob/master/src/font.js#L35

Is there any more help doc which I miss.

**Comment by Jolg42** [comment]
It's a standard unix timestamp in seconds that will be translated to the old Apple Mac timestamp in the background.
https://github.com/opentypejs/opentype.js/blob/4e0bb99d4471369a68b53dd4ef2db9eca73a5b04/src/tables/head.js#L34

**Comment by orklann** [comment]
Thank you for your quick reply.
