### ISSUE TITLE
Path.toPathData and Path.toSVG - X Axis is flipped

### ISSUE THREAD

**Issue by panayotoff** [opentypejs/opentype.js#369]
I'm using OpentypeJS to create SVGs for single glyph characters. However, when I draw the SVGs, the glyph is flipped on it's X axis ( upside down ). Even the ./bin/test-render in the repo generates flipped SVG path data.

## Expected Behavior

1) Load font
2) Get glyph path data with glyph.path.toSVG()
3) Use the path data to render proper glyph

## Current Behavior

1) Load font
2) Get glyph path data with glyph.path.toSVG()
3) Use the path data to render glyph, the glyph is rendered upside down.

## Possible Solution

Fix path commands. 

## Steps to Reproduce (for bugs)

Just run the /bin/test-render  from the repo

## Your Environment

* Version used:  0.11.0
* Font used: Every font

**Comment by ryami333** [comment]
Can confirm!

**Comment by Jolg42** [comment]
1.2.1 is released with this change 😃

**Comment by Jolg42** [comment]
I will undo in next version as it's breaking the current output

**Comment by alephzero** [comment]
I think this issue is still outstanding.

**Comment by cjhgit** [comment]
Same error in newest version (1.3.4)

**Comment by Connum** [comment]
At first I thought that maybe the `toSVG()` functionality was only implemented for the unicode text rendering test tool, but it actually existed several years earlier. It baffles me that it seems to always have resulted in upside down glyphs and never been fixed. Font paths and SVG use an inverted y axis, so while one goes down (0,0 is in the top-left corner), the other one goes up (0,0 is in the bottom-left corner).

With #568, I'll change the code to output adjusted SVG paths by default, and make the test tool force the unadjusted paths.
