### ISSUE TITLE
How to change values for hhea, os2 tables

### ISSUE THREAD

**Issue by orklann** [opentypejs/opentype.js#371]
What I expect to work is like this:

```
font.tables.hhea.ascender = 1024;
```

But it does not work at all.

**Comment by Connum** [comment]
This issue is quite old, but I'm going to answer this anyway. Opentype.js abstracts that value into font.ascender, that's why changing the table value doesn't do anything. But it would be a good idea to use getters and setters to make sure that changing one of them also reflects back to the other.
