### ISSUE TITLE
new Glyph({ advanceWidth: 0 }) does not set the advanceWidth property

### ISSUE THREAD

**Issue by dougrich** [opentypejs/opentype.js#375]
## Expected Behavior
```js
const g0 = new opentype.Glyph({
  advanceWidth: 10
})
console.log(g0.advanceWidth) // this should be 10
const g1 = new opentype.Glyph({
  advanceWidth: 0
})
console.log(g0.advanceWidth) // this should be 0
```

## Current Behavior
```js
const g0 = new opentype.Glyph({
  advanceWidth: 10
})
console.log(g0.advanceWidth) // this correctly logs 10
const g1 = new opentype.Glyph({
  advanceWidth: 0
})
console.log(g0.advanceWidth) // this is undefined, which causes 'not a number' errors if we try to download the font
```

## Possible Solution
Location: `src/glyph.js:85` currently reads:
```js
if (options.advanceWidth) {
  this.advanceWidth = options.advanceWidth
}
```

It should probably read:
```js
if (options.advanceWidth != null) {
  this.advanceWidth = options.advanceWidth
}
```

Explicitly checking for a `null` or `undefined` value rather than relying on falsiness.

I suspect this same problem also occurs for `xMin`, `yMin`, `xMax` and `yMax`

## Steps to Reproduce (for bugs)
See the above code samples.

It doesn't really crash until I go to download: at that point I get back:

`Error: Glyph <name> (<index>): advanceWidth is not a number.`

Which makes sense, since at that point it is undefined.

## Context
Specifically I'm trying to create a set of 0 width glyphs that would overlap with each other, sort of like the underlying components of [Hangul](https://en.wikipedia.org/wiki/Hangul). The idea is each horizontal spot would be made up of smaller glyphs overlapped, with an explicit separator character.

I have the workaround of explicitly setting the `advanceWidth` after the constructor.

## Your Environment
* opentyp.js@0.11.0, installed via npm
* Node v10.9.0
* Ubuntu 18.04.1 LTS

## Aside

Big fan of the project. It's nice to have a very comprehensive OpenType font parser in native js.

I'd be open to creating a pull request for my proposed change above along with tests.

**Comment by Connum** [comment]
This was fixed via #430
