### ISSUE TITLE
How to detect font type (OTF/TTF)

### ISSUE THREAD

**Issue by jsieler** [opentypejs/opentype.js#388]
We have a lot of fonts, partially downloaded or from our customers. The problem is that their extensions are partially wrong, where .ttf named file might be OTF file type. Is there any magic how to detect OTF or TTF file type from font so i can rename them in a bunch?

Thanks!

**Comment by stone-zeng** [comment]
`font.outlinesFormat = 'truetype'` is TTF, while `font.outlinesFormat = 'cff'` is OTF (OpenType/CFF).

**Comment by jsieler** [comment]
Thanks!

**Comment by yvele** [comment]
Any way to also detect WOFF?
