### ISSUE TITLE
Can this module convert otf file to ttf file?

### ISSUE THREAD

**Issue by littlee** [opentypejs/opentype.js#393]
as the title asked.

when calling `new opentype.Font`, I don't know how to specify the font format

**Comment by yne** [comment]
opentype.js can only generate OpenType Font, but you can use the excelent [fontforge](https://github.com/fontforge/fontforge) editor to convert your OTF to TTF using the following example command:

```bash
fontforge -lang=ff -c 'Open("example.otf");AutoHint();Generate("example.tff")'
```
