### ISSUE TITLE
Async await not working

### ISSUE THREAD

**Issue by ricardomatias** [opentypejs/opentype.js#406]
## Expected Behavior
Async await should import font and return it.

## Current Behavior
Using async await successfully fetches the font (200 on Network tab), but it doesn't return the font object.

1. openType.load('assets/fonts/Moon2.0-Light.otf')
2. loads font
3. doesn't return anything

## Context
Just trying to load a font.

## Your Environment
* Version used: 1.1.0
* Font used: Moon2.0-Light.otf
* Browser Name and version: Vivaldi (Chromium) 2.4.1488.35 (Stable channel) (64-bit)
* Operating System and version (desktop or mobile): Mac OS X 10.14.6

**Comment by haakenlid** [comment]
I tried to use opentype.js in an observablehq notebook and had the same problem.
I ended up writing an async wrapper function.
```
async function loadFont (url) {
  return await new Promise(
    (resolve, reject) => opentype.load(
      url, (err, font) => err ? reject(err) : resolve(font)
    )
  )
}
```

**Comment by tomershvueli** [comment]
I am also seeing this issue. Quite frustrating especially considering this is in the README documentation. In the meantime, @haakenlid 's solution worked for me!

**Comment by Jolg42** [comment]
1.2.1 is released with this change 😃
