### ISSUE TITLE
Incorrect constant name or value in code example:

### ISSUE THREAD

**Issue by ryami333** [opentypejs/opentype.js#407]
https://github.com/opentypejs/opentype.js/blob/89939f159597b841e9465bf897591813c3be2ad1/src/glyph.js#L279

Should either be:
```js
const TWO_PI = Math.PI * 2;
```
OR:
```
const PI_SQ = Math.pow(Math.PI, 2);
```

Not sure which is incorrect, the math or the const name.

**Comment by Jolg42** [comment]
I removed the var 😄
