### ISSUE TITLE
Version 1.1.0 Does not contain latest fixes

### ISSUE THREAD

**Issue by odeadglaz** [opentypejs/opentype.js#408]
When trying to install version 1.1.0, Latest fixes are not being pulled.
## Expected Behavior
When pulling the latest 1.1.0 Version, I expected the package content to match the master branch.

## Current Behavior
Latest changes are not being pulled. example of one is :
package.json file module entry point's to src/opentype.js file instead of ES module file

## Possible Solution
New patch version release.

## Steps to Reproduce (for bugs)
1. Pull latest version
2. Open package json
3. If compared to this master, it's not up to date.

## Your Environment
* 1.1.0

**Comment by Jolg42** [comment]
1.2.0 is released with this change 😃
