### ISSUE TITLE
Write OS/2 Table with sxHeight & sCapHeight

### ISSUE THREAD

**Issue by signalwerk** [opentypejs/opentype.js#409]
When I do the following: 

```js
var test = new Font({
  familyName: "TestFont",
  styleName: "Bold",
  unitsPerEm: 2048,
  ascender: 1500,
  descender: -500,
  glyphs: [
    new Glyph({
      name: ".notdef",
      advanceWidth: 650,
      path: new Path()
    })
  ]
});

test.tables.os2 = {
  ...test.tables.os2,
  sxHeight: 1100,
  sCapHeight: 1400
};
test.download();
```

and convert then the font with [Fonttools TTX](https://github.com/fonttools/fonttools) I see the following (wrong) values:

```xml
<sxHeight value="750"/>
<sCapHeight value="0"/>
``` 

Is there a logic to it? Or what do I do wrong?

**Comment by fizfaz** [comment]
If I understand it correctly: the values for sxHeight and sCapHeight are calculated here: https://github.com/opentypejs/opentype.js/blob/342fac9e81a34ef08b69c5f08a0ec71727e0b832/src/tables/sfnt.js#L248-L249

and not settable. Does this help?

**Comment by signalwerk** [comment]
@fizfaz thanks a lot for pointing to the specific code! I Made a PR here: https://github.com/opentypejs/opentype.js/pull/410

**Comment by Jolg42** [comment]
Thank you for opening the issue, I'm now closing it as the other PR was merged and published see https://github.com/opentypejs/opentype.js/pull/422

**Comment by signalwerk** [comment]
perfect! thank you!
