### ISSUE TITLE
OpenType not displaying Urdu, Korean scripts

### ISSUE THREAD

**Issue by cynthiaxhua** [opentypejs/opentype.js#412]
I loaded the Noto font (https://www.google.com/get/noto/) into openType but cannot get it to display a number of foreign scripts including Korean and Urdu. The Noto font is meant to be compatible with these languages. 

For example, if you try to paste this Urdu character ( چار ) into the OpenType Example Test page here (https://opentype.js.org/) and load in the Noto Font .ttf (download here https://www.google.com/get/noto/), you will get just tofu. 

Any tips on working with foreign scripts?

**Comment by robsch** [comment]
I think there is a problem on https://opentype.js.org. In the browser console 

> Error: lookupType: 7 - substFormat: 1 is not yet supported

gets shown. But it seems to work anyway if your using the library directly.

**Comment by KKzLEO** [comment]
+1 😥

**Comment by ILOVEPIE** [comment]
A lot of foreign scripts require special font features that aren't supported yet. We're working on it though.

**Comment by Connum** [comment]
See https://github.com/opentypejs/opentype.js/issues/627#issuecomment-1773311283
