### ISSUE TITLE
substFormat: 1 is not yet supported for Calibri Font

### ISSUE THREAD

**Issue by xornor-web** [opentypejs/opentype.js#415]
## Expected Behavior
SubSet Font not creating for Calibri Font

## Current Behavior
Error: lookupType: 7 - substFormat: 1 is not yet supported
    at FeatureQuery.getLookupMethod (..\node_modules\opentype.js\dist\opentype.js:12239:20)
    at FeatureQuery.lookupFeature (..\node_modules\opentype.js\dist\opentype.js:12295:34)
    at ..\node_modules\opentype.js\dist\opentype.js:12720:43
    at Array.forEach (<anonymous>)
    at Bidi.latinLigature (..\node_modules\opentype.js\dist\opentype.js:12718:28)
    at C:\Users\Xornor\nodeJSpro\pptx2html\node_modules\opentype.js\dist\opentype.js:12911:24
    at Array.forEach (<anonymous>)
    at Bidi.applyLatinLigatures (..\node_modules\opentype.js\dist\opentype.js:12910:13)
    at Bidi.applyFeaturesToContexts (..\node_modules\opentype.js\dist\opentype.js:12932:30)
    at Bidi.processText (..\node_modules\opentype.js\dist\opentype.js:12947:15)

## Steps to Reproduce (for bugs)
1. I am creating calibri.ttf suset font from Node but error occurring 
```
let filePath = "calibri.ttf";
let desFilePath = "sub_calibri.ttf";
var font = opentype.loadSync(filePath);
var subsetFont = undefined;
var glyphs = font.stringToGlyphs("1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ");
subsetFont = new opentype.Font({
    familyName: font.names.fontFamily.en,
    styleName: font.names.fontSubfamily.en,
    unitsPerEm: font.unitsPerEm,
    ascender: font.ascender,
    descender: font.descender,
    glyphs: glyphs
});
fs.writeFileSync(desFilePath, Buffer.from(subsetFont.toArrayBuffer()));
var fontEnable = opentype.loadSync(desFilePath);
```

**Comment by Connum** [comment]
I'm currently working on writing support for lookup type 6 (format 1 and 3 are done) and hope to find the time to implement all other missing lookup types as well.

**Comment by devlfm** [comment]
I'm having this error an Arial too. I updated to last release 1.3.3 and still getting this error. How can I solve this?

**Comment by devlfm** [comment]
Does using ttf version of the fonts solves this issue?

**Comment by devlfm** [comment]
Using otf version of the font is a possible workaround?

**Comment by mehmetdemiray** [comment]
I observed that this problem occurs in texts that mix Arabic and Latin characters, and I tried almost all Arabic fonts available on Google Fonts. The only font that didn't throw an error is this one:

https://fonts.google.com/specimen/Beiruti
