### ISSUE TITLE
Request to publish the current master to the npm package

### ISSUE THREAD

**Issue by kboda** [opentypejs/opentype.js#420]
The npm package seems to be outdated, since it contains the old path for the "module" key in package.json (points inside src instead of dist).

This leads to importing the non compiled version in eg. the text-to-svg package, so when using it in a web app, the bundle includes arrow functions which breaks the parsing in IE 11.

I would really appreciate if you could publish the current master branch, with that it works flawlessly.

## Expected Behavior
The npm package is in sync with the master branch.

## Current Behavior
It contains outdated files.

## Possible Solution
Publish master to the npm package.

If i use it directly with the git url it works as expected: https://github.com/kboda/text-to-svg/blob/useLocally/package.json#L50

**Comment by rjgotten** [comment]
> the old path for the "module" key in package.json (points inside src instead of dist).

The "module" field is supposed to point to an ES module, which is what `./src` contains.
A `./dist` folder that's precompiled for browsers should have the "browser" field as its convention.
And a `./dist` folder that's meant for Node.js should use the "main" field.

**Comment by Jolg42** [comment]
1.2.0 is released finally 🎊 https://github.com/opentypejs/opentype.js/blob/master/RELEASES.md#120-april-13-2020

@rjgotten is there something to fix in the package.json? Could you make a PR or post the changes needed here?

**Comment by Jolg42** [comment]
I added a default export in 1.3.0
