### ISSUE TITLE
How to interpolate between two master fonts?

### ISSUE THREAD

**Issue by michintosh** [opentypejs/opentype.js#424]
Hi,

I'm trying for a project to create a live interpolation between two "master" fonts (one is Source Sans Regular and the other Source Sans Black) giving to a slider a value with range 0 -100 that will be lerped in order to give the font the current interpolated value.

To do so, I've loaded both fonts and, while looping over all of the glyphs paths commands, I've created another subset of commands that have the result of each lerped coordinate.

It works just fine with some characters, but with other it gets really "dirty" and "fuzzy", with bezier curves not being handled so well.

I've read in other posts that this could be related to some characters of the two weights not having the same number of points, but it's strange to see it happening also with some glyphs that have the same amount of point (inspected in Adobe Illustrator).

I've also tried using different file formats (.ttf, .otf and .woff), but even if the errors seems a little different, they're still there.

Is there maybe another way of achieving this result? 

Thx

**Comment by Connum** [comment]
I would say this is outside of the scope of this library.
