### ISSUE TITLE
Use Without Canvas

### ISSUE THREAD

**Issue by brandonmcconnell** [opentypejs/opentype.js#425]
Is there a way to use Opentype.js without using canvas? I won't be doing any font "point" manipulation. I'm looking to copy the contents from one glyph into another, essentially switching/shuffling characters, writing the new collection to a new .ttf file and then use that font live on the page. Is that possible?

**Comment by antonytse** [comment]
It can be used without Canvas. I think you may directly use this library with Node.js for this use case.

**Comment by Connum** [comment]
Closing as it has been answered.
