### ISSUE TITLE
Composite glyph 2x2 transformation has wrong order.

### ISSUE THREAD

**Issue by treeform** [opentypejs/opentype.js#432]
If you take a look at this line here:

https://github.com/opentypejs/opentype.js/blob/14a22d19c5bcebc13340dd650a590fbd77b063e8/src/tables/glyf.js#L161

It does not match what is in freetype: 

https://github.com/aseprite/freetype2/blob/45524679c6798b3d8b75ab03d54a53bf46912871/src/truetype/ttgload.c#L674

The 01 and the 10 need to be flipped in order to work.

See the "+" character on this font:
https://github.com/google/fonts/blob/master/ofl/changa/static/Changa-Bold.ttf

![image](https://user-images.githubusercontent.com/125948/80655072-a0dc2000-8a32-11ea-8f45-88d41dad1060.png)

**Comment by Connum** [comment]
still reproducible (1.3.4 and master):
[changa (3).zip](https://github.com/opentypejs/opentype.js/files/13468291/changa.3.zip)

**Comment by Connum** [comment]
the order during parsing actually matches the pseudo code given in the spec: https://learn.microsoft.com/en-us/typography/opentype/spec/glyf#code-try-0
So we should flip the values in the calculation.

@brawer Another one for you?
