### ISSUE TITLE
Variable Font / JavaScript / Generative Type

### ISSUE THREAD

**Issue by HiImDaniel-type** [opentypejs/opentype.js#433]
Hello guys, im Daniel, a graphic designer from Portugal ending my master degree about manipulation of variable fonts to produce kinetic typography experiments.
Im creating this topic because my main ideia is to create a web system where the user can manipulate a variable font (that i created) and add some graphic elements (circles.. generative elements etc...)
Since until now in p5.js the only way to add a variable font is through DOM elements, not on canvas, how on earth will i be able to add generative elements to a variable font ?
Hope you can help me!

Have a good day!

**Comment by Jolg42** [comment]
Hi Daniel!

I'm not sure how to do that but you may be interested by this: 
 
https://twitter.com/axis_praxis/status/1257373825676783616?s=19

**Comment by HiImDaniel-type** [comment]
Jolg42, is there any possibility with opentype.js and variablefont.js to get acess to the variable axes in p5.js ?

**Comment by Connum** [comment]
Variable font rendering landed via #699.
