### ISSUE TITLE
Finding a single path down the centre of text

### ISSUE THREAD

**Issue by lukefisklennon** [opentypejs/opentype.js#434]
It's a bit hard to explain in words, so here's some images:

![image](https://user-images.githubusercontent.com/43358885/81575261-2cb65a80-93ea-11ea-9f53-5a3dfa5dfd5f.png)![image](https://user-images.githubusercontent.com/43358885/81575339-422b8480-93ea-11ea-8431-aa16a26a5c50.png)

On the left is a rendering of the letter "j" with the font Beth Ellen. It is derived from the SVG path data which was generated by the module `text-to-svg` (which uses opentype.js).

On the right is the same rendering, but with blue lines hand-drawn down the 'centre' of the text, to illustrate what I'm trying to achieve. This is a single path representing the letter, instead of a path enclosing the letter.

I'm just wondering if and how it would be possible to achieve this? Thanks in advance!

**Comment by danmarshall** [comment]
I don't think this is a simple computation. See this for an example of a technique that might be used: https://observablehq.com/@veltman/centerline-labeling
