### ISSUE TITLE
Panose parsing?

### ISSUE THREAD

**Issue by shash7** [opentypejs/opentype.js#437]
Is there a way to parse panose numbers with opentype.js?

## Expected Behavior
This is not a bug

## Current Behavior
opentype.js currently give a array of panose numbers in the os2 table but doesn't describe them. I would like to know if parsing the panose array is possible through opentype.js

## Context
I'm trying to build an automatic parser for my project getsnapfont.com and a panose parser would be highly valuable.

## Your Environment
NA

**Comment by Jolg42** [comment]
This is probably the documentation you need https://docs.microsoft.com/en-us/typography/opentype/spec/os2#panose

**Comment by shash7** [comment]
Thanks for the link @Jolg42 
It seems that there's no deterministic way to parse Panose and plus, there's missing Panose information for many fonts out there. Do you know any other of getting font width, boldness, category type, etc from a font file?
