### ISSUE TITLE
Adding support for Variable Fonts, by integrating SamsaCore.js 

### ISSUE THREAD

**Issue by wentin** [opentypejs/opentype.js#444]
Would love OpenType.js to support Variable Fonts, can read VF related data tables, and render SVGpath for variable fonts's named instances and custom instances.

SamsaCore.js currently does these features above, but lacking other OpenType.js basic features, like compose a word, getting kerning, etc. Seems it would be beneficial for both projects to merge effort.

https://github.com/Lorp/samsa/blob/master/docs/samsa-core.md

**Comment by vinuel** [comment]
There is also variableFont.js ... very small and easy to use. I use it in combination with opentype.js. Maby interessting:
https://github.com/Monotype/variableFont.js

**Comment by Typogram** [comment]
> There is also variableFont.js ... very small and easy to use. I use it in combination with opentype.js. Maby interessting:
> https://github.com/Monotype/variableFont.js

The variableFont.js only read feature data from variable fonts, it doesn't support drawing/render variable fonts (given axis setting) to pathData. Samsa draws variable fonts as pathData that you can use in Canvas or SVG

**Comment by Typogram** [comment]
> There is also variableFont.js ... very small and easy to use. I use it in combination with opentype.js. Maby interessting: https://github.com/Monotype/variableFont.js

variableFont.js doesn't render variable fonts' path data. it only read its axes data.

**Comment by Connum** [comment]
Variable font rendering landed via #699
