### ISSUE TITLE
a simple text "Pepe ❤️ Potamo" get a crossed square char (no char) after the heart

### ISSUE THREAD

**Issue by IJOL** [opentypejs/opentype.js#446]
I'm using the latest npm version, and as far i've debugged it seems to me that the tockenizer spits a no char in the place of a secod utf8 byte, something like that 

i've get this tokens you can se a non character after the heart this gives us the crossed square char

  tokens: 
   [ Token { char: 'M', state: [Object], activeState: [Object] },
     Token { char: 'a', state: [Object], activeState: [Object] },
     Token { char: 'u', state: [Object], activeState: [Object] },
     Token { char: 'r', state: [Object], activeState: [Object] },
     Token { char: 'y', state: [Object], activeState: [Object] },
     Token { char: ' ', state: [Object], activeState: [Object] },
     Token { char: '❤', state: [Object], activeState: [Object] },
     Token { char: '️', state: [Object], activeState: [Object] },
     Token { char: ' ', state: [Object], activeState: [Object] },
     Token { char: 'A', state: [Object], activeState: [Object] },
     Token { char: 'l', state: [Object], activeState: [Object] },
     Token { char: 'e', state: [Object], activeState: [Object] } ],

**Comment by solomancode** [comment]
Hi @IJOL ,

The *Red Heart* emoji requires two points of encoding.
1. The Unicode *Heavy Black Heart* character ❤ **u+2764**
2. The variation character **u+fe0f**

Currently the Tokenizer doesn't support multiple code-point characters decomposition like the ❤️ emoji. So it assigns the emoji to the first token and leaves the second token as a placeholder for the other code-point.

You can safely ignore the empty variation character placeholder ''.

I hope that helps,
Regards.
