### ISSUE TITLE
arabic script supported?

### ISSUE THREAD

**Issue by zoghal** [opentypejs/opentype.js#46]
hi, 
i test arabic/persian font with opentype.js demo : http://ritaco.github.io/opentype.js/index.html
 but the cuurent version of opentype.js can not support features isol, init, medi, fina in GSUB table.

Please guide me to add this feature.
thanks.

**Comment by defue** [comment]
Any news on Arabic language support? Are any right-to-left languages supported?

**Comment by davelab6** [comment]
@defue what do you mean by "arabic language support"? I think you would need harfbuzz transpiled to javascript.

**Comment by devongovett** [comment]
[fontkit](http://github.com/devongovett/fontkit) has an arabic shaper (mostly ported from harfbuzz).

**Comment by zoghal** [comment]
if need javascript reshaper can use this [persian-reshaper](https://github.com/font-store/persian-reshaper)

**Comment by fdb** [comment]
The scope of OpenType.js is not to do perfect typesetting for all locales. For that you'll probably need OpenType.js + Harfbuzz.

Alternatively please check out @devongovett's excellent [fontkit](https://github.com/devongovett/fontkit).

**Comment by defue** [comment]
By "Arabic language support" I meant ability of "stringToGlyphs" method to correctly convert a string into Arabic glyphs. I'll look at the options advised here. Thank you all!

**Comment by fdb** [comment]
You're right, I thought you were talking about the type setting. The stringToGlyphs we probably do want. There we still need some work to support the OpenType (I think `GSUB`?) tables.

**Comment by defue** [comment]
Is there anything I can do to speed up the development of Arabic and other right-to-left languages support?

**Comment by davelab6** [comment]
It seems fontkit is pulling ahead for that usecase

**Comment by fdb** [comment]
I'm currently finishing my PhD and don't have the time required to implement those OpenType features. As @davelab6 suggested you might want to look into FontKit for this.

**Comment by Jolg42** [comment]
I guess we can close this issue as I just merged #359 
Feel free to reopen if needed!
