### ISSUE TITLE
Finding it hard as a newbie to understand documentation

### ISSUE THREAD

**Issue by laimoh** [opentypejs/opentype.js#460]
## Context
After snapping the path to a grid I wish to generate a new font from the new paths formed. Could the process be explained conceptually? I just need some more information. My current use case takes in a text input and then the text snaps to a grid and changes form. Now I wish to download this new path of letters (whichever are on the canvas) as characters.

## Your Environment

* Version used:
* Font used: Source Code Pro
* Browser Name and version: Chrome

**Comment by axkibe** [comment]
I don't quite get what you want.

You have different "layers" conceptionally speaking.

You have the font (which is a set of drawing instructions for all letters there are)
You have text
You can use the font with text to create paths...
(These you optinally can snap to a grid..)
And you use the paths to draw on a canvas.

If you want to create a new Font, you would change the letters, but you don't use text input, and you can't snap onto a grid depending on the letter positions.

PS: The snapping to grid demo opentype.js is IMO just some silly, simple demonstration for something you need the path information of letters and you could never do with canvas.drawText(). I don't think it's a sensible process by itself.

**Comment by Connum** [comment]
Closing this after 3 years of inactivity
