### ISSUE TITLE
Font file is accepted only when its not uploaded via input file

### ISSUE THREAD

**Issue by monkeySalater** [opentypejs/opentype.js#462]
## Intro
Sorry for my english, it is not my native language. 
Also sorry if am missing something easy, im a learning noobie, go easy on me.

## The Issue
I basically tried to do exactly what is on this site: https://opentype.js.org/font-inspector.html .
Here is my code yet:
![Screenshot 2020-12-29 at 18 29 49](https://user-images.githubusercontent.com/76745928/103302399-d7c06680-4a03-11eb-818e-bb9955d3155c.png)
The "local font" that I'm reading from my local server, works fine, I get response like this: (just an object with the info I need)
<img width="690" alt="Screenshot 2020-12-29 at 18 32 51" src="https://user-images.githubusercontent.com/76745928/103302571-44d3fc00-4a04-11eb-893d-fbb832346268.png">
However, when I try to load the copy of the same file as the user in the browser, I get an error:
<img width="695" alt="Screenshot 2020-12-29 at 18 35 10" src="https://user-images.githubusercontent.com/76745928/103302724-97151d00-4a04-11eb-80ca-68c45d758c15.png">
I also tried logging the file if it's broken or anything, I get this the console:
<img width="283" alt="Screenshot 2020-12-29 at 18 35 49" src="https://user-images.githubusercontent.com/76745928/103302758-ad22dd80-4a04-11eb-9ca9-16054e5fc5ac.png">

## Context
Im trying to build website for checking mistakes for typographs.

## Your Environment

* Version used: downloaded 2 days  ago
* Font used: Space Grotesk ect. (tried few of them)
* Browser Name and version: Safari, latest one
* Operating System and version (desktop or mobile): Macos Big Sur
* Link to your project: https://we.tl/t-o4NAaTr5Ud

## Summ
I don't really know what I'm doing, I would love any response with any ideas how to make it work. 
THANKS!!!

**Comment by mollthecoder** [comment]
It seems to be sending a 404 error page when p5 loads it. Maybe check to see if the hosting server is working properly.

**Comment by yne** [comment]
The URL you are fecthing is incorrect `.../[object%20File]`
This is why you get a 404 HTML page which is not parsable by Opentype
