### ISSUE TITLE
invalid font and missing properties creating glyphs programmatically

### ISSUE THREAD

**Issue by gurki** [opentypejs/opentype.js#472]
## Hi opentype folks!

I'm trying to export a pixel font I designed, that I'm storing as bit-arrays.
I'm programmatically creating a glyph for each letter, however the exported font is invalid (not recognized by Windows Font Viewer).
Looking at the font in [fontdrop](fontdrop.info), the paths are all there, but all bounding box and advanceWidth information is missing for some reason.
It's set correctly per glyph, not sure what's going wrong there.
Even more curious, when I cut off the export below unicode 112, the font is at least recognized correctly by windows, still without glyph properties though.

This is the relevant piece of code.

```js
function convertJsonFont( data ) {

    const notdefGlyph = new opentype.Glyph({
        name: '.notdef',
        unicode: 0,
        advanceWidth: 300,
        path: new opentype.Path(),
    });

    let glyphs = [ notdefGlyph ];

// ...

            const path = pathFromBits( item.bits );
            const unicode = parseInt( item.unicode.substr( 2 ), 16 );

            const glyph = new opentype.Glyph({
                name: item.name,
                index: count++,
                unicode: unicode,
                advanceWidth: 100 * ( path.box.xMax + 2 ),
                xMin: 100 * path.box.xMin,
                yMin: 100 * path.box.yMin,
                xMax: 100 * path.box.xMax,
                yMax: 100 * path.box.yMax,
                path: path.path,
            });

            glyphs.push( glyph );

// ...

    const font = new opentype.Font({
        familyName: 'MiniGent',
        styleName: 'Regular',
        unitsPerEm: 400,
        ascender: 400,
        descender: -100,
        glyphs: glyphs,
// ...
    });

    return font;

// ...
```

## Steps to Reproduce
The code is available at [github.com/gurki/pixeltex](https://github.com/gurki/pixeltex/blob/font-export/exporter/exporter.js).
It can be run directly from there.

## Your Environment
* Version used: @latest
* Font used: custom paths
* Browser Name and version: Chrome 89.0.4389.114
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: [pixeltex](https://github.com/gurki/pixeltex).

**Comment by yne** [comment]
Running the following
```js
convertJsonFont({"Latin Alphabet": {'A': { bits: [0,1,0,1,0,1,1,1,1,1,0,1], unicode: "U+0041", name: "Latin Capital Letter A", symbol: 'A' }}}).download()
```

Generate the expected output:

![image](https://user-images.githubusercontent.com/5113053/164548595-367dfca0-855b-4643-9b46-fb1e1afea3cf.png)

I don't know from where fontdrop get it {x,y}{Min,Max} value from but I tried with a working font and it also returned `undefined`.

I don't have a windows machine to test on they engine.

**Comment by yne** [comment]
I guess it's good now.
