### ISSUE TITLE
Missing acute chars

### ISSUE THREAD

**Issue by devlfm** [opentypejs/opentype.js#484]
Font Sofia and font Sail do not render glyphs with acute accent.

![image](https://user-images.githubusercontent.com/11923375/127786042-19c6dcb7-df3d-464d-a8fb-6499b18add9a.png)

BAD: https://www.fontsquirrel.com/fonts/sofia

GOOD: https://fonts.google.com/specimen/Sofia

**Comment by ILOVEPIE** [comment]
This is probably a ligature bug or something. This needs to be looked into.

**Comment by Connum** [comment]
Fixed with the current master:
![image](https://github.com/opentypejs/opentype.js/assets/13076806/a81ca082-25b5-4184-9722-ef59b967371c)
