### ISSUE TITLE
HMTX incorrect parsing

### ISSUE THREAD

**Issue by sigurdle** [opentypejs/opentype.js#489]
Looking at the source, and it seems that the HMTX table is incorrectly parsed

This is the spec:
https://docs.microsoft.com/en-us/typography/opentype/spec/hmtx

You have:
for (let i = 0; i < numGlyphs; i += 1) {
        // If the font is monospaced, only one entry is needed. This last entry applies to all subsequent glyphs.
        if (i < numMetrics) {
            advanceWidth = p.parseUShort();
            leftSideBearing = p.parseShort();
        }

        const glyph = glyphs.get(i);
        glyph.advanceWidth = advanceWidth;
        glyph.leftSideBearing = leftSideBearing;
    }

It should be:
for (let i = 0; i < numGlyphs; i += 1) {
        if (i < numMetrics) {
            advanceWidth = p.parseUShort();
        }
// NOTE: There's a left side bearing for all glyphs, the shortened varient applies only to advanceWidth
        leftSideBearing = p.parseShort();

        const glyph = glyphs.get(i);
        glyph.advanceWidth = advanceWidth;
        glyph.leftSideBearing = leftSideBearing;
    }

**Comment by ILOVEPIE** [comment]
The way the code is written is consistent with the microsoft documentation.

**Comment by sigurdle** [comment]
I'm not sure about that.
In the spec it sais:

"If numberOfHMetrics is less than the total number of glyphs, then the hMetrics array is followed by an array for the left side bearing values of the remaining glyphs
"

You don't seem to be reading in that array, but instead using the last leftSideBearing value
