### ISSUE TITLE
Add leftSideBearing (lsb) to `new Glyph`

### ISSUE THREAD

**Issue by adri326** [opentypejs/opentype.js#500]
The `new Glyph` constructor allows the user to set the `advanceWidth` of the glyph, but not the `leftSideBearing` ([see here](https://github.com/opentypejs/opentype.js/blob/master/src/glyph.js#L69-L87)).
However, [this value is read by `Glyph::getMetrics`](https://github.com/opentypejs/opentype.js/blob/master/src/glyph.js#L234), meaning that an user can still define it manually as a property of their `Glyph` instance.

## Expected Behavior

The following code should create a new `Glyph` and set its `leftSideBearing` property.

```js
let my_glyph = new opentype.Glyph({
	name: "My Glyph",
	unicode: 65,
	path: new opentype.Path(),
	advanceWidth: 400,
	leftSideBearing: -100,
});

assert(my_glyph.getMetrics().advanceWidth === 400); // works
assert(my_glyph.getMetrics().leftSideBearing === -100); // should work
```

## Current Behavior

The `leftSideBearing` option is ignored and `getMetrics` defaults to a value of `0`:

```js
console.log(my_glyph.getMetrics()); /* currently returns:
{
	xMin: ...,
	xMax: ...,
	yMin: ...,
	yMax: ...,
	advanceWidth: 400,
	leftSideBearing: 0,
}
*/

assert(my_glyph.getMetrics().advanceWidth === 400); // works
assert(my_glyph.getMetrics().leftSideBearing === -100); // currently fails
```

## Possible Solution

Add the following piece of code in `Glyph.prototype.bindConstructorValues`:

```js
if ('leftSideBearing' in options) {
    this.leftSideBearing = options.leftSideBearing;
}
```

This issue can be worked around by setting `my_glyph.leftSideBearing = -100;` manually.

## Context

This issue appeared as I was trying to encode combining diacritics on [online-pixel-font-creator](https://github.com/adri326/online-pixel-font-creator).
After manually setting the `leftSideBearing` property, it would finally show up in the glyph inspector. [See the commit that adds the workaround.](https://github.com/adri326/online-pixel-font-creator/commit/fb7eda67bda2d7d8c60caa395280e2b7b273a50a).

My tool generated the following font files with the `Font::download` method.

- before commit fb7eda6: 
[before-fb7eda6.zip](https://github.com/opentypejs/opentype.js/files/7780304/before-fb7eda6.zip)
- after commit fb7eda6: 
[after-fb7eda6.zip](https://github.com/opentypejs/opentype.js/files/7780306/after-fb7eda6.zip)

## Your Environment

* Version used: `@latest` on `jsdelivr.net`, which happens to be `1.3.4`
* Font used: my own - [font-source.zip](https://github.com/opentypejs/opentype.js/files/7780318/font-source.zip)
* Browser Name and version: `Mozilla Firefox 95.0b8`
* Operating System and version (desktop or mobile): `Linux anarchy 5.15.2-arch1-1 x86_64 GNU/Linux`
* Link to your project: https://github.com/adri326/online-pixel-font-creator/

**Comment by yne** [comment]
Nice investigation, the solution looks nice.
Could you create a PR so it could be reviewed ?
