### ISSUE TITLE
loadFromUrl does not support Node.js environment

### ISSUE THREAD

**Issue by antoineol** [opentypejs/opentype.js#506]
Here is a PR to solve it: #503 . Please let me know if anything is wrong about it :)

loadFromUrl implementation relies on XHR2, which is only available in the browser. I tried a polyfill, but the available XHR2 polyfill seems to have a bug causing the process to hand for ~120 seconds in some cases.

The PR provides a nodejs implementation to load from a URL.

## Expected Behavior

loadFromUrl works in nodejs.

## Current Behavior

It fails by default on nodejs (no XHR) and I couldn't find a polyfill working as expected.

## Possible Solution

C.f. PR #503

## Steps to Reproduce (for bugs)

1. On nodejs, load a font from a URL instead of file system.
2. It fails.

## Context

C.f. PR for motivations and context.

## Your Environment

* Version used: 1.3.4
* Font used: https://github.com/Templarian/MaterialDesign-Webfont/blob/master/fonts/materialdesignicons-webfont.ttf?raw=true
* Browser Name and version: nodejs 16
* Operating System and version (desktop or mobile): Windows 10 desktop
* Link to your project: private project

**Comment by ILOVEPIE** [comment]
@Connum we should probably merge this at some point to get the library working with node versions lower than 18.

**Comment by Connum** [comment]
I just added a [PR on the fork](https://github.com/antoineol/opentype.js/pull/1) to test this. When @antoineol merges it, @ILOVEPIE can do the review
