### ISSUE TITLE
Save/export font as WOFF (in Node.js)

### ISSUE THREAD

**Issue by yvele** [opentypejs/opentype.js#507]
I searched everywhere but I didn't found in the documentation how to export a font to WOFF in Node.js.
I'm able to use `font.toArrayBuffer()` to get the OTF.

Is there a way to directly get a WOFF binary?

Back in 2015 some people where talking about that feature:
 - https://github.com/opentypejs/opentype.js/issues/103#issuecomment-85984620
 - https://github.com/opentypejs/opentype.js/issues/103#issuecomment-86485934

Maybe a workaround to convert OTF to WOFF using an other library?

I found a [ttf2woff](https://github.com/fontello/ttf2woff) library.. but no way to get an otf2woff equivalent 🤔  (even though [some websites](https://www.google.com/search?q=otf+2+woff) allows converting OTF to WOFF online).

Maybe related to:
 - https://github.com/opentypejs/opentype.js/issues/388
 - https://github.com/opentypejs/opentype.js/issues/393

**Comment by yne** [comment]
Hi,

[woff2_compress](https://github.com/google/woff2) works fine for me.

```bash
sudo apt install woff2
woff2_compress my.otf # will create my.woff2
```

Don't expect WOFF/2 output as it would require additional compression algorithms (zlib for WOFF and [brotli](https://github.com/google/brotli) for WOFF2)

It's better to write programs that do one thing and do it well ;)
