### ISSUE TITLE
Handling unicode ranges and glyph lookup

### ISSUE THREAD

**Issue by zoomclub** [opentypejs/opentype.js#51]
Opentype puts a whole new spin on working with a new music notation OTF called Bravura. The Bravura font is an open standard and large as it covers most music symbols known to mankind. It is defined in the unicode user space as multiple sections grouping the many types/classes of music symbols into unicode ranges. Browse the ranges and diverse music glyphs here : http://www.smufl.org/version/latest

Not all music publishing will require all the sections defined by Bravura. What would be helpful in Opentype is to be able to be able to parse only given unicode ranges or a specific list into a Opentype Font. Maybe this list format can be defined as JSON to act as a parse filter?

It would also be good to see what unicode code point a parsed glyph has and then to be able to lookup a given parsed glyph or range of glyphs by their unicode values.

**Comment by Connum** [comment]
Closing this old issue. I don't think we need to implement some higher-level functionality for this. You can already filter the glyphset in order to create a subset.
