### ISSUE TITLE
Support multi-character emoji

### ISSUE THREAD

**Issue by forresto** [opentypejs/opentype.js#511]
This issue with monochrome Noto Emoji is distinct from the color emoji issue (#193).

#338 added support for non-Basic-Multilingual-Plane (BMP) characters, but uses `Array.from`, which doesn't account for combined emoji.

It seems that Opentype.js has the glyph information needed, but the initial text-to-glyph translation is the issue:

![image](https://user-images.githubusercontent.com/395307/166242754-65e95f63-79cb-4ad3-8e4c-f87310a8aefc.png)
https://opentype.js.org/glyph-inspector.html

## Expected Behavior

Calling `notoEmojiFont.draw(context, "👨‍👩‍👧‍👦")` should render
![image](https://user-images.githubusercontent.com/395307/166223470-afd9ff31-c504-420b-aa71-b59d949e7d42.png)

## Current Behavior

Calling `notoEmojiFont.draw(context, "👨‍👩‍👧‍👦")` renders
![image](https://user-images.githubusercontent.com/395307/166223510-9ca5f5db-839f-40eb-a450-69527a2d245c.png)

## Possible Solution

0. If "ccmp" is not supported yet and would cover this, this issue can be closed as a duplicate of https://github.com/opentypejs/opentype.js/issues/443.

1. [Intl.Segmenter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) is a native solution, but [isn't supported by Firefox yet](https://caniuse.com/mdn-javascript_builtins_intl_segmenter).

```js
const splitSegmentArray = (string) => Array.from(new Intl.Segmenter().segment(string)).map(x => x.segment);
console.log(splitSegmentArray("😅👨‍👩‍👧‍👦💖👩‍💻💔👩‍🌾🧡👨🏽‍🌾💜🖖🏾🌈"))
```

2. [graphemer](https://github.com/flmnt/graphemer) is a library-based solution. (It is a fairly big library.)

3. [twemoji-parser](https://github.com/twitter/twemoji-parser) is focused on parsing emoji sequences, so it's smaller than graphemer.

## Steps to Reproduce (for bugs)

Live demo: https://gm69qn.csb.app

1. Call `notoEmojiFont.stringToGlyphs("👨‍👩‍👧‍👦")` and get glyphs for "👨👩👧👦" interspersed with the combiner (`"uni200D"`) instead of the one glyph for the combined family.

![image](https://user-images.githubusercontent.com/395307/166223776-698d561e-0892-49e8-9104-974a83df24b0.png)

2. Same for other combined emoji, like 👩‍💻, 👩‍🌾, 👨🏽‍🌾, 🖖🏾

## Context

We're adding support for emoji to [Cuttle CAD](https://cuttle.xyz/), which can render various fonts as vectors for laser cutting, etc.

## Your Environment

* Version used: 1.3.4
* Font used: [Noto Emoji](https://fonts.google.com/noto/specimen/Noto+Emoji) ([ttf](https://fonts.gstatic.com/s/notoemoji/v23/bMrnmSyK7YY-MEu6aWjPDs-ar6uWaGWuob_10jwvS-FGJCMY.ttf))
* Browser Name and version: Various tested
* Operating System and version (desktop or mobile): Mac OS desktop
* Link to your project: https://gm69qn.csb.app

**Comment by forresto** [comment]
It seems like `font.tables.gsub` has the info needed to combine these. Is that something that I can enable with an option?
<img width="730" alt="image" src="https://user-images.githubusercontent.com/395307/166437928-ac7c82b3-6425-4852-ae2b-b336dab17720.png">

**Comment by forresto** [comment]
Looking at #443 I thought this was worth a try:
```js
notoEmojiFont.substitution.add(
  "ccmp", 
  notoEmojiFont.substitution.getFeature('ccmp')
);
```
but got:
> Error: Ligature: unable to modify coverage table format 2

**Comment by forresto** [comment]
In addition to the `ccmp` substitutions, https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block) need to be taken into account. For example, `"☠"` vs `"☠️"`.

**Comment by jamesjoung** [comment]
Im also looking for a workaround for this.
It would be nice to support it or have workaround?

**Comment by forresto** [comment]
Here's my workaround. 

```js
// Opentype.js doesn't actually support these substitutions, so we'll have to
// search them manually
const substitutions = font.substitution.getFeature("ccmp");

const glyphs = font
  .stringToGlyphs("👨‍👩‍👧‍👦")
  // Discarding these makes the substitution search work for emoji sequences
  // with variation selectors
  // https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)
  .filter((glyph) => glyph.index <= 1850);
let glyph;
if (glyphs.length === 1) {
  glyph = glyphs[0];
} else if (glyphs.length > 1) {
  const indexes = glyphs.map((glyph) => glyph.index);
   const sub = substitutions.find((substitution) => equals(substitution.sub, indexes));
  if (sub) {
    glyph = font.glyphs.get(sub.by);
  }
}
if (glyph) {
  // Do something
} else {
  // Expected to find a match
  throw new Error(`${native} (${id}) - couldn't find a glyph :(`);
}
```

```js
/** Custom equals function that can also check lists. */
function equals(a, b) {
  if (a === b) {
    return true;
  } else if (Array.isArray(a) && Array.isArray(b)) {
    if (a.length !== b.length) {
      return false;
    }
    for (let i = 0; i < a.length; i += 1) {
      if (!equals(a[i], b[i])) {
        return false;
      }
    }
    return true;
  } else {
    return false;
  }
}
```

Caveats:

This only works for one emoji. To replace the glyphs in an arbitrary string, we would also need tokenizer logic.

Only tested with [Noto Emoji](https://fonts.google.com/noto/specimen/Noto+Emoji).

![image](https://user-images.githubusercontent.com/395307/168656036-b127186e-2d66-42c8-9802-42efa7cb875c.png)

**Comment by ILOVEPIE** [comment]
here's the different options: https://medium.com/making-faces-and-other-emoji/emoji-fonts-technically-40f3fdc0869e
I'd recommend at leas supporting COLR/CPAL as it's probably the most widely supported one and one of the most implemented in fonts. It would also probably be a good idea to implement CBDT/CBLC support as well.

**Comment by TonyJR** [comment]
ccmp looks like an enforcement feature.  It's not display in feature list, but always runs before decode a text.
![image](https://github.com/opentypejs/opentype.js/assets/7473679/83900d86-94e1-40ea-bbf1-0c75f5f363c2)
https://learn.microsoft.com/en-us/typography/script-development/standard
Maybe we can add a preprocessing process in Font.stringToGlyphs() ?
