### ISSUE TITLE
Raw table binary data from the font not exposed

### ISSUE THREAD

**Issue by pranayaggarwal** [opentypejs/opentype.js#516]
Hi opentype team,

First of all, huge thanks for such a wonderful work that has been put in opentype.js

In my project I wanted to run some heuristics over **cmap** and **OS/2** table data however it seems that any of table doesn't have the raw binary data exposed for consumption. Please can this be supported.

cc @yne & @adri326

**Comment by yne** [comment]
Hi,
yes, the table parse/make stage is not exposed as public API as it is subject to change/refactor.
So OpenType.js won't offer a Byte-level table view anytime soon. Only an object level (see: `myFont.tables.colr`)

But if you need a raw scripting access to any TTF/OTF table, there is a tool for that:
https://fonttools.readthedocs.io/en/latest/ttx.html

Good luck :+1:
