### ISSUE TITLE
Recreate textPath with pure JS

### ISSUE THREAD

**Issue by lachlansmith** [opentypejs/opentype.js#519]
I need to create text on an arc without transform attributes so ```<textPath>``` is unfortunately not the answer, but I would like to know how it works. I figured the best to ask such a question would be here, given the entire community loves opentype.js.

The approach I've taken is to parse text into glyphs. Then somehow use the glyphPath commands to place the characters one by one onto the path. I figured [forEachGlyph](https://github.com/opentypejs/opentype.js/blob/423b611adade6bf84ac3be58362f3d670a41bcb1/src/font.js#L296) would be a good place to start. Any assistance would be much appreciated. If this already exists please please point me in the right direction. 
```
const textPath = (text: string, path: string, font: Buffer, fontSize: number): string => {
    let f = opentype.parse(font.buffer);

    let fullPathOnPath = new Path();

    f.forEachGlyph(
        text,
        0,
        0,
        fontSize,
        {},
        (glyph, gX, gY, gFontSize) => {
            let glyphPath = glyph.getPath(gX, gY, gFontSize, {}, this);

            // transform glyphPath to be on path

            fullPathOnPath.extend(glyphPath);
        }
    );

    return fullPathOnPath;
};
```

**Comment by danmarshall** [comment]
Hello, apologies to point you to another library (which uses opentype.js) but you can do this with Maker.js - here's a couple of examples:
https://maker.js.org/playground/?script=text-on-path
https://maker.js.org/playground/?script=text-on-chain
https://maker.js.org/docs/advanced-drawing/#Layout%20on%20a%20path

**Comment by lachlansmith** [comment]
Definitely don't apologise. I'm stoked there's a fully-fledged library that handles this. Either my google abilities are lacking or maker.js has horrible SEO. Thanks for the help
