### ISSUE TITLE
Weird squiggle in Bookman bold font

### ISSUE THREAD

**Issue by noobd3v** [opentypejs/opentype.js#525]
A weird squiggle that can be seen by zooming in on the bottom left of the letter was caused when creating svg path for Bookman bold ttf file. TTF file is added in the zip file attached. This type of anomaly is present in other character created for the font also which is causing other issues while using this data for further processing. 
![image](https://user-images.githubusercontent.com/13329441/198951720-f389c8bb-3eda-40bc-8984-700b68dc5c7e.png)
[bookman1.zip](https://github.com/opentypejs/opentype.js/files/9898795/bookman1.zip)

## Expected Behavior

SVG Path generated:-
M103.04 91.04L103.04 91.04L114.08 119.68L108.96 121.76L102.56 121.76Q97.60 115.84 92.48 111.36Q87.36 106.88 81.92 104L81.92 104Q77.12 101.44 71.52 100Q65.92 98.56 59.36 98.24L59.36 98.24Q59.20 98.24 58.88 98.24Q58.56 98.24 58.24 98.24L58.24 98.24Q57.76 98.24 57.28 98.24Q56.80 98.24 56.32 98.24L56.32 98.24Q55.84 98.40 55.36 98.40Q54.88 98.40 54.40 98.40L54.40 98.40Q53.28 98.56 52.08 98.80Q50.88 99.04 49.76 99.36L49.76 99.36Q48.64 99.52 47.68 100Q46.72 100.48 45.92 101.12L45.92 101.12Q44.32 102.24 43.44 103.60Q42.56 104.96 42.24 106.72L42.24 106.72Q42.08 108.32 41.92 110Q41.76 111.68 41.76 113.44L41.76 113.44L41.76 137.76L46.08 137.76Q52.16 138.08 56.08 137.12Q60 136.16 61.92 134.24L61.92 134.24Q63.84 132.32 65.20 128.32Q66.56 124.32 67.20 118.40L67.20 118.40L72.64 118.08L79.04 118.08L79.04 165.92L72.64 165.92L67.20 165.92Q67.04 164.32 66.72 162.56Q66.40 160.80 66.08 159.04L66.08 159.04Q65.60 157.28 64.88 155.60Q64.16 153.92 63.04 152.32L63.04 152.32Q61.44 149.92 59.60 148.48Q57.76 147.04 55.52 146.56L55.52 146.56Q53.28 146.08 50.88 145.84Q48.48 145.60 45.76 145.60L45.76 145.60L41.76 145.44L41.76 177.12Q41.76 177.92 41.76 178.56Q41.76 179.20 41.76 179.84L41.76 179.84Q41.76 180.16 41.76 180.48Q41.76 180.80 41.92 181.12L41.92 181.12Q41.92 181.60 42 181.92Q42.08 182.24 42.08 182.56L42.08 182.56Q42.24 183.52 42.48 184.32Q42.72 185.12 42.88 185.92L42.88 185.92Q43.20 186.72 43.44 187.44Q43.68 188.16 44.16 188.64L44.16 188.64Q44.96 189.76 46 190.56Q47.04 191.36 48.32 191.84L48.32 191.84Q49.60 192.32 51.04 192.64Q52.48 192.96 53.92 193.12L53.92 193.12Q54.24 193.12 54.56 193.20Q54.88 193.28 55.20 193.28L55.20 193.28Q55.52 193.28 55.84 193.36Q56.16 193.44 56.48 193.44L56.48 193.44Q64.96 193.12 72 191.36Q79.04 189.60 84.80 186.08L84.80 186.08Q90.88 182.40 96.56 176.88Q102.24 171.36 107.68 164L107.68 164L114.08 163.84L119.20 165.92L104.64 200L98.24 200L4.96 200L4.96 195.20L6.56 195.04L12.96 195.04L13.28 195.20L6.88 195.20L7.52 195.04L7.84 195.04L8.16 195.04Q9.60 195.04 10.96 194.80Q12.32 194.56 13.60 194.08L13.60 194.08Q14.88 193.76 16 192.80Q17.12 191.84 17.76 190.24L17.76 190.24Q18.08 189.44 18.40 188.64Q18.72 187.84 18.88 186.72L18.88 186.72Q19.04 185.76 19.12 184.64Q19.20 183.52 19.36 182.40L19.36 182.40Q19.36 182.08 19.36 181.76Q19.36 181.44 19.36 180.96L19.36 180.96Q19.36 180.64 19.36 180.32Q19.36 180 19.36 179.68L19.36 179.68Q19.36 178.88 19.36 178.32Q19.36 177.76 19.36 177.12L19.36 177.12L19.36 176L19.36 175.20L19.36 116L19.36 115.04Q19.36 115.04 19.36 114.88Q19.36 114.72 19.36 114.56L19.36 114.56Q19.36 114.56 19.36 114.40Q19.36 114.24 19.36 114.08L19.36 114.08Q19.36 110.40 19.04 107.44Q18.72 104.48 17.92 101.92L17.92 101.92Q17.28 99.52 14.64 98.08Q12 96.64 7.36 96.32L7.36 96.32L4.96 95.84L4.96 91.04L11.36 91.04L103.04 91.04L103.04 91.04Z

## Steps to Reproduce (for bugs)

1.Upload bookman bold ttf file for font on https://opentype.js.org/
2. Create svg path for some characters for example E or O 
3. Use the path created to notice the issue.

## Your Environment

* Version used: 
* Font used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by kenmcd** [comment]
The defect is in the font.
The example font is a very old AllType conversion.
And there are defects in the outlines.

E - the lower left foot has a loop on the outline.

![E-lower-left](https://user-images.githubusercontent.com/844920/199074971-f98b8ee8-e60d-44b3-acb0-e57fbb5756ce.png)

O - the inner left contour has a jog in the outline (and extra nodes) 
![O-inner-left](https://user-images.githubusercontent.com/844920/199075290-523ad489-956b-4601-a385-ac3e33766774.png)

The issue is the fonts.
Get better versions.

**Comment by noobd3v** [comment]
Yes it seems like an issue with fonts tried a different version and it worked. Thanks for looking into it.
