### ISSUE TITLE
Support using a plain SVG file as a glyph

### ISSUE THREAD

**Issue by fabiospampinato** [opentypejs/opentype.js#526]
## Expected Behavior

I don't know if this would be considered out of scope or not, but I'd really like if this library supported importing a raw SVG string as a glyph, which would cut out all sorts of intermediary dependencies one currently needs when generating an .odt font.

## Current Behavior

It doesn't seem possible to import raw SVG.

## Possible Solution

Maybe the Glyph class could get an additional `svg` property that internally extracts the path from the SVG?

**Comment by Connum** [comment]
I'm working on some SVG optimizations in the linked branch (still WIP). If this gets merged, you'll be able to do the following:
```js
const pathFromSVG = Path.fromSVG(pathStringOrSVGPathElement);
// or
// pathFromSVG = (new Path()).fromSVG(pathStringOrSVGPathElement);
const glyphOptions = {
// ....
path: pathFromSVG
// ...
};

new Glyph(glyphOptions);
```

**Comment by fabiospampinato** [comment]
Awesome, thanks!
