### ISSUE TITLE
Font Names that are platform specific get overwritten by last name of that language.

### ISSUE THREAD

**Issue by ILOVEPIE** [opentypejs/opentype.js#527]
## Expected Behavior
Fonts names should be either parsed into a hierarchy first by platform and then by language or first by language and then by platform.

## Current Behavior
A font's names object will contain only the last corresponding name for that language instead of having them separated by platform, this means that it is impossible to reproduce an identical font file and prevents accessing platform specific font names.

## Possible Solution
We need to modify [these lines](https://github.com/opentypejs/opentype.js/blob/2a6c2f61630ec1f5f580f092e42631e95ad8bb48/src/tables/name.js#L653-L660) to generate a table with all the data correctly; also any methods/functions that utilize the names table will have to be updated to reflect the changes.

## Steps to Reproduce (for bugs)
1. load a font with different platform-specific names.
2. inspect the font's name property.

## Context
I'm writing a JavaScript subtitles renderer that has to emulate windows font handling so I need to select my fonts using the windows platform specific font names.

## Your Environment
* Version used: v1.3.4
* Font used: Any
* Browser Name and version: Mozilla Firefox 106.0.5 (64-bit)
* Operating System and version (desktop or mobile): Arch Linux x86_64 (6.0.7-zen1-1-zen) sway (wayland; wl-roots)
* Link to your project: https://github.com/SABRE-JS/SABRE.js

**Comment by ILOVEPIE** [comment]
I will submit a PR to fix this.

**Comment by Connum** [comment]
Fixed with #542
