### ISSUE TITLE
How to get Use Typo Metrics ?

### ISSUE THREAD

**Issue by dehyang** [opentypejs/opentype.js#538]
The decision is to use hhea, typo (OS/2) and win (usWin)

**Comment by ILOVEPIE** [comment]
Uh... I'm not exactly sure what you mean. What you wrote is a little vague.

**Comment by dehyang** [comment]
> Uh... I'm not exactly sure what you mean. What you wrote is a little vague.

There is an attribute in FontCreator. How can I use opentype.js to get it?

This attribute relates to the calculation of font position

![image](https://user-images.githubusercontent.com/83799221/216932776-9bd71ad5-1ce5-4949-8ed7-0ca21384d723.png)

**Comment by kenmcd** [comment]
`USE_TYPO_METRICS` is a flag in the `fsSelection` field of the `OS/2` table.

https://learn.microsoft.com/en-us/typography/opentype/spec/os2#fsselection

**Comment by dehyang** [comment]
> `USE_TYPO_METRICS` is a flag in the `fsSelection` field of the `OS/2` table.
> 
> https://learn.microsoft.com/en-us/typography/opentype/spec/os2#fsselection

感谢

但是我用fsSelection 试过，结合 浏览器表现 与 FontCreator 查看 找不出任何规律取值

**Comment by ILOVEPIE** [comment]
The USE_TYPO_METRICS flag is part of the OS/2 table, it's just a setting and is accessible via the OS/2 table that Opentype.js parses.
