### ISSUE TITLE
Standard Web Fonts

### ISSUE THREAD

**Issue by TheRealTR** [opentypejs/opentype.js#571]
Can opentype access the standard browser fonts, as opposed to reloading from a file? If so, can it access any font cached in the browser?

**Comment by Connum** [comment]
There's the [Local Font Access API](https://developer.chrome.com/en/articles/local-fonts/), right now only available in desktop Chromium browsers. Even if it was more widely available, I don't think this would be something the library will ever include, as you can just load the font data into it anyway.

I haven't tried it myself yet, but I'll do so later and maybe will be able to provide a demo.

**Comment by Connum** [comment]
Here's the demo:
1. open https://opentype.js.org/font-inspector.html in a Chromium browser
2. open the dev console (F12)
3. Run the following in the console and allow font access
```js
(await window.queryLocalFonts(
  /*
  {
  postscriptNames: ['Verdana', 'Verdana-Bold', 'Verdana-Italic'],
  }*/
  ))
  [0] // loads the first system font it can find, or you could query by postscript name
  .blob()
  .then((blob) => blob.arrayBuffer())
  .then(opentype.parse)
  .then(onFontLoaded);
```

**Comment by TheRealTR** [comment]
Thanks so much! We’re building an Electron app, so Chrome would be standard- not sure about mobile.As an alternative, could you pass a base64 encoded font file?On Feb 23, 2023, at 9:15 AM, Connum ***@***.***> wrote:﻿
Here's the demo:

open https://opentype.js.org/font-inspector.html in a Chromium browser
open the dev console (F12)
Run the following in the console and allow font access

(await window.queryLocalFonts(
  /*
  {
  postscriptNames: ['Verdana', 'Verdana-Bold', 'Verdana-Italic'],
  }*/
  ))
  [0] // loads the first system font it can find, or you could query by postscript name
  .blob()
  .then((blob) => blob.arrayBuffer())
  .then(opentype.parse)
  .then(onFontLoaded);

**Comment by Connum** [comment]
Sure, you just need to convert it to a ByteArray, that's what opentype's `parse()` method expects as a parameter.
