### ISSUE TITLE
Error: Unsupported OpenType signature wOF2

### ISSUE THREAD

**Issue by tt-abetemadi** [opentypejs/opentype.js#601]
Using opentypejs cdn to load the font endups to the `Error: Unsupported OpenType signature wOF2` error 

## Expected Behavior
load the font

## Current Behavior
Error: Unsupported OpenType signature wOF2

## Steps to Reproduce (for bugs)
1. download roboto regular ttf font from `https://dl.dafont.com/dl/?f=roboto` or any other source
2. upload it on your server. and provide the uploaded font asset url to opentype js load url and await for its promise to resolve
3. it ends with `Error: Unsupported OpenType signature wOF2`

## Your Environment
Shopify liquid template engine
* Version used: tried every version of opentype
* Font used: roboto-regular.ttf, woff, woff2
* Browser Name and version: chrome
* Operating System and version (desktop or mobile): 
* Link to your project:

**Comment by Connum** [comment]
Please see #183 and #518.

**Comment by tt-abetemadi** [comment]
@Connum Thank you for your assistance! I was able to optimize the code using the following approach:

```js
    this.font = await fontBuffer
      .then((buffer) => Module.decompress(buffer))
      .then((buffer) => opentype.parse(Uint8Array.from(buffer).buffer));
  }
```

**Comment by pcldev** [comment]
@ab-etemadi Can you help me where the Module is declared.
