### ISSUE TITLE
Path properties do not translate in Path.toSVG(2)

### ISSUE THREAD

**Issue by Pleket** [opentypejs/opentype.js#613]
## Expected Behavior
The fill color, stroke color and stroke thickness properties in the Path object should be included in the conversion of path object to path XMLElement. If the object contains these properties, the XMLElement should contain these same properties, as shown in the example here: https://www.w3.org/TR/SVG/paths.html#PathData

## Current Behavior
Currently, the properties are touched upon in the readme, but not actually included in the conversion when running the path.toSVG() function. I noticed that they are included in the code, but an incorrect if statement has an unwanted outcome that is not actually tested in the test cases. 

## Possible Solution
Resolve the contradicting code in path.js and add test cases for the additional properties. 

## Steps to Reproduce (for bugs)
1. Load a .ttf font
2. Obtain the path object of a specific glyph by calling glyph.getPath(0, 0, 72)
3. Do not add a fill color (or set path.fill = 'black') and do console.log(path.toSVG(2)). The fill property is not included. Similarly, visualizing yields a white canvas. 

## Context
Visualize the font. 

## Your Environment
* Version used: 
* Font used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Pleket** [comment]
Additionally, I have noticed that there seems to be no support for multicolored fonts. That is, if the colors of say a .ttf font are part of the conversion at all. Currently, only black is possible, while FontLab allows the user to import .ttf fonts while preserving the colors.

**Comment by Connum** [comment]
Could you elaborate on the wrong code so that anyone wanting to fix this doesn't have to do all the debugging on their own? Or even better, make a PR with the fix if you can!

**Comment by Connum** [comment]
I think you're talking about 
```js
if (this.fill && this.fill !== 'black') {
        if (this.fill === null) {
            svg += ' fill="none"';
        } else {
            svg += ' fill="' + this.fill + '"';
        }
}
```
?

That's true, `this.fill === null` can never be true because of `this.fill` in the previous if statement, which should rather be `this.fill !== undefined && this.fill !== 'black'`. I'll fix that soon™ and we also need to respect those properties in `toDOMElement()`.

However, stroke and stroke color are already working as intended if I didn't miss anything?
