### ISSUE TITLE
Make Font object structure more similar to OTF file

### ISSUE THREAD

**Issue by kuckir** [opentypejs/opentype.js#67]
I see you are creating about 20 properties on File object (ascender, copyright, descender, description, designer ...). All these properties are already stored in Font.tables. 

I think it is convenient for user to get these data right from tables, he can learn something about font file structure at the same time. I don't see any reason for such redundancy, it also makes file object "messy".

**Comment by Connum** [comment]
Closing this issue after +8 years of inactivity
