### ISSUE TITLE
how can I  get font metadata by font file (.ttf,.otf,.woff2,.woff) by simple method?

### ISSUE THREAD

**Issue by hys-c** [opentypejs/opentype.js#674]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Font used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Connum** [comment]
Please put a little more effort into your ticket. What kind of metadata do you need and what part of the documentation is unclear?

**Comment by ILOVEPIE** [comment]
Closed due to no response.
