### ISSUE TITLE
Writing slow (30+ seconds) for certain fonts (CJK, Noto Chinese)

### ISSUE THREAD

**Issue by Balearica** [opentypejs/opentype.js#682]
For most fonts, Opentype.js can write a font file using `font.download()` or `font.toArrayBuffer()` in a fraction of a second.  However, certain fonts that include many characters are subject to extreme runtimes.  

This occurs with both Simplified Chinese variants of the Noto family.  Using `NotoSansSC-Regular.ttf` (available [here](https://fonts.google.com/noto/specimen/Noto+Sans+SC)), running `font.toArrayBuffer()` from the console after loading in the [example site](https://opentype.js.org/) took 36 seconds.  Similarly, trying to write `NotoSerifSC-Regular.otf` (available [here](https://fonts.google.com/noto/specimen/Noto+Serif+SC)) running `font.toArrayBuffer()` took 33 seconds.

Not all CJK fonts are this slow--I tested a couple others from Google Fonts that took 4-5 seconds.  However, as I've never experienced anything like this with fonts that only support Latin characters, I'm guessing it's related to the number of glyphs in these fonts.

I will investigate more myself and try and fix in a PR. 

## Your Environment

* Version used: 3fce140bda37e557d2ecb206094428240bfd1615
   * Latest commit as of the time of this writing
* Font used: Noto Sans Simplified Chinese, Noto Serif Simplified Chinese
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10

**Comment by Balearica** [comment]
This ended up being due to excessive re-allocation of memory by using `d = d.concat(...)` rather than `push`.  This is fixed in the PR linked above.

**Comment by Connum** [comment]
Closed via #683
