### ISSUE TITLE
Naming Table Parsing seems buggy

### ISSUE THREAD

**Issue by MichaelLaw2003** [opentypejs/opentype.js#710]
## Expected Behavior

Naming Table (name-table) is expected to be displayed in pages similar to [font inspector](https://opentype.js.org/font-inspector.html).

## Current Behavior

I've downloaded and updated opentype.js via npm and downloaded the font inspector demo HTML file from this respository.

I've downloaded site.css and site.js from [opentype.js.org](https://opentype.js.org/).

I've manually setted the local relative pathes correctly, and run the font inspector demo page on local host.

Everything else is behavioring as expected, except for the naming table. The naming table is empty. (It's not "undefined", it's just empty.)

## Possible Solution

I tried downloading the opentype.js from [opentype.js.org](https://opentype.js.org/), and the bug is fixed.

Seeing that opentype.js has been updated in recent weeks, I'm not quite sure if the version from the [opentype.js.org](https://opentype.js.org/) is the latest stable version.

I ran the buggy script downloaded (and updated) via npm, and fetched the parsed font info directly, and found out that the platform infomation is missing, causing the function `displayNames` in font-inspector.html (line 229) not working properly.

## Steps to Reproduce (for bugs)

1. Download and update opentype.js via npm and download the font inspector demo HTML file from this respository (under the folder `./docs`).

2. Download site.css and site.js from [opentype.js.org](https://opentype.js.org/).

3. Manually set the local relative pathes correctly, and run the font inspector demo page on local host.

4. Load a local font file, and check the "Naming table" toggle list.

## Your Environment

* Version used: 1.3.4
* Font used: Roboto Regular (ttf font, downloaded from Google Fonts)
* Browser Name and version: Microsoft Edge, 124.0.2478.80
* Operating System and version (desktop or mobile): Desktop, Windows 10 Pro, 64x
* Link to your project:

**Comment by Connum** [comment]
Please see the latest [release notes](https://github.com/opentypejs/opentype.js/releases/tag/1.3.4)
