### ISSUE TITLE
Local build rules were deleted this should not have happened.

### ISSUE THREAD

**Issue by ILOVEPIE** [opentypejs/opentype.js#721]
Our code-style rules got deleted. This should not have happened.

**Comment by ILOVEPIE** [comment]
@Connum can you fix this, I'm sure this was just a mistake by @yne.

**Comment by yne** [comment]
you mean this file ?

https://github.com/opentypejs/opentype.js/blob/master/eslint.config.mjs

**Comment by yne** [comment]
I just tested to remove a semicolon and run `npm run lint` and the eslint [rules](https://github.com/opentypejs/opentype.js/blob/master/eslint.config.mjs) are still enforced ...
So I'm not sure to understand what you are talking about @ILOVEPIE 

![image](https://github.com/opentypejs/opentype.js/assets/5113053/4199f44a-ac3d-4372-aea4-d948338a999b)

**Comment by ILOVEPIE** [comment]
The local build rules file.

**Comment by yne** [comment]
all of them have been discuted in the PR you approved

**Comment by ILOVEPIE** [comment]
No, they worked.

**Comment by yne** [comment]
good news 🎉 

I love issues that get solved without any code changes

**Comment by ILOVEPIE** [comment]
> good news 🎉 
> 
> I love issues that get solved without any code changes

No, they workED. they do NOT now.

**Comment by yne** [comment]
oh sorry, so which rule exaclty ?
the rules I tried worked

**Comment by ILOVEPIE** [comment]
> oh sorry, so which rule exaclty ?
> the rules I tried worked 

The ones you deleted.

**Comment by yne** [comment]
Before refactor, there were exactly [2 local build rules](https://github.com/opentypejs/opentype.js/blob/c6a3cb8d9b7f10079b6b24dd453065820134b82d/eslint-local-rules.js)

-  `import-extensions` : which is already enforced in mjs mode, for example if I try to import without extension: 
![image](https://github.com/opentypejs/opentype.js/assets/5113053/152c0d85-27ad-4bd2-a8bb-b65f4cbbdf53)


-  `ban-foreach` : which is now enforced [here](https://github.com/opentypejs/opentype.js/blob/master/eslint.config.mjs#L44) and I confirm it's still working
![image](https://github.com/opentypejs/opentype.js/assets/5113053/44b5f546-d04a-4c35-bb7e-37478294fbf5)

So please be more precise

**Comment by ILOVEPIE** [comment]
Sorry, I think somehow I messed it up on the branch I was working on locally so that it wasn't working and when I saw it was deleted I panicked. My bad.
