### ISSUE TITLE
`Uncaught (in promise) ReferenceError: exports is not defined` when using in Next.js

### ISSUE THREAD

**Issue by r-bt** [opentypejs/opentype.js#746]
When using the opentype.js package in Next.js after running `getPath` I get the error:

`Uncaught (in promise) ReferenceError: exports is not defined`

The stacktrace leads to this as the culprit:

```javascript
if (exports.DEBUG) {
                console.log('---EXEC FPGM---');
                fpgmState.step = -1;
}
```

## Expected Behavior

exports should be defined

## Current Behavior

exports is not defined in NextJS

## Steps to Reproduce (for bugs)
See: https://github.com/r-bt/test-opentype

1. See `src/app/page.tsx`
2. Run code with `npm run dev` and see error in console

## Context
I am trying to use the [jscad-text](https://github.com/jscad-community/jscad-text) library which uses the getPath function

## Your Environment

* Version used: 1.3.4
* Font used: Habana
* Browser Name and version: Firefox 128.0 
* Operating System and version (desktop or mobile): macOS 14.4 (23E214)
* Link to your project:

**Comment by Connum** [comment]
Although it is the most recent release, 1.3.4 is outdated. This bug has been fixed in the master branch.

**Comment by r-bt** [comment]
Awesome, is the recommendation to clone the repo and build it myself then?

**Comment by Connum** [comment]
Yes, the current master can be used as a github dependency via `npm install "https://github.com/opentypejs/opentype.js.git#master"` or by building the dist files from the repository
