### ISSUE TITLE
How can I create or obtain a single stroke line font using opentype.js? (and it can be used for japanese)

### ISSUE THREAD

**Issue by phong-hopee** [opentypejs/opentype.js#748]

**Comment by phong-hopee** [comment]
<img width="1114" alt="Screen Shot 2024-07-29 at 10 29 44" src="https://github.com/user-attachments/assets/bc6aa590-983e-442d-ab03-58ae4dc8d720">

Now I am using notosanjs and it creates multi-stroke.

**Comment by forresto** [comment]
Here is some info about "single line" and "hairline" versions of fonts.

> Both fonts come in both a single-line version and a hairline version; different software programs will use different formats.

https://missymeyer.com/dear-agatha-font

So it depends how you will display the font, if you want to encode it with open paths (single line) or closed paths (hairline).
