### ISSUE TITLE
strange behavior when two contours overlap

### ISSUE THREAD

**Issue by potatoShield** [opentypejs/opentype.js#750]
i'm trying to minify font file from an variable font with specific font weight，but letter A is not rendering as expectation on browser: 
![image](https://github.com/user-attachments/assets/132370bc-33ad-4105-89db-96fa8f31bb4a)

wondering if there's any solution for this?

```
const font = opentype.parse(arrayBuffer); // i'm using SourceHanSans-VF.ttf
const hhea = font.tables.hhea
const head = font.tables.head
const name = font.tables.name
const notdefGlyph = font.glyphs.get(0);

const minText = 'A';
const list = font.stringToGlyphs(minText);
const glyphList = list.map((glyph) => {
  const config = font.variation.getTransform({ ...glyph, name: glyph.name || 'uni' + glyph.unicode, }, { wght: 300 })
  return config
})

const newFont = new opentype.Font({
  familyName: 'OpenTypeSans',
  styleName: 'Medium',
  unitsPerEm: head.unitsPerEm,
  ascender: hhea.ascender,
  descender: hhea.descender,
  glyphs: [notdefGlyph, ...glyphList]
});

fs.writeFileSync("./out.ttf", Buffer.from(newFont.toArrayBuffer()));
```

**Comment by herrstrietzel** [comment]
From you rendering it seems like path directions are changing. E.g. if the outer shape is drawn in clockwise and the the middle bar is drawn in clockwise direction. See this[ stackoverflow post](https://stackoverflow.com/questions/78881320/where-two-m-z-sequences-meet-the-background-color-shows-through#comment139076091_78881320).   
AFAIK opentype.js doesn't support truetype export - all contours are converted from glyf (ttf) to CFF (otf) - so the newly compiled font should in fact be a .otf.  
Maybe the command conversion introduces this error. Can you reproduce this error with another VF font?

**Comment by potatoShield** [comment]
> From you rendering it seems like path directions are changing. E.g. if the outer shape is drawn in clockwise and the the middle bar is drawn in counter-clockwise direction. See this[ stackoverflow post](https://stackoverflow.com/questions/78881320/where-two-m-z-sequences-meet-the-background-color-shows-through#comment139076091_78881320). AFAIK opentype.js doesn't support truetype export - all contours are converted from glyf (ttf) to CFF (otf) - so the newly compiled font should in fact be a .otf. Maybe the command conversion introduces this error. Can you reproduce this error with another VF font?

I printed the path data and paste it on a playground, it works as expectation, so maybe it's not the same problem as the post refered? also i‘ve tried with some other different VF fonts such as SourceHanSerifSC-VF.ttf \ SourceHanSans-VF.ttf ，this problem still exists;
`const minText = 'A';
  const list = font.stringToGlyphs(minText);
  const glyphList = list.map((glyph) => {
    const config = font.variation.getTransform({ ...glyph, name: glyph.name || 'uni' + glyph.unicode, }, { wght: 300 })
    console.log(config.path)
    console.log(config.path.toPathData())
    return config
  })`

![image](https://github.com/user-attachments/assets/deb2fd23-6e8a-4885-ad51-f05a6d91ba74)
![image](https://github.com/user-attachments/assets/29b2dda3-22f8-446b-b3ed-0050d3fa3000)

**Comment by potatoShield** [comment]
here's my minified font files：（ttf & otf）
[minify-font.zip](https://github.com/user-attachments/files/16834671/minify-font.zip)

**Comment by herrstrietzel** [comment]
Thanks a lot for the excellent clarifications! You're right my linked explanation is obviously rather a generic explanation. However, the path direction/winding concept is most likely responsible for this issue. Which begs the question at which point the path directions are messed up when compiling the new font.  Maybe it doesn't affect the SVG rendering output options but affects the new font output. Another sneaky suspicion: opentype.js (v2.0.0) still probably only supports a CFF(version1) output. In this version overlapping contours are not permitted. See also ["Microsoft typography: Comparison of 'glyf', 'CFF ' and CFF2 tables"](https://learn.microsoft.com/en-us/typography/opentype/spec/glyphformatcomparison) and Pomax's post ["Update docs for Font.getPath to explain what happens with cutout subpaths"](https://github.com/opentypejs/opentype.js/issues/347)

**Comment by herrstrietzel** [comment]
I can't really reproduce this issue at least not using the subset you provided. Also inspecting it in fontlab the path directions are fine. See codepen example based on your otf version applied as a data URL: https://codepen.io/herrstrietzel/pen/YzoJaWB. Can you detect any differences that might be browser specific?

**Comment by kenmcd** [comment]
Overlaps are normal in variable font.
So part of your conversion process must "remove overlaps" if you do not want them.
You can use tools such as fonttools or foundrytools-cli to easily remove the overlaps.

Most modern browsers can handle overlaps even in static fonts. 
The most common offender in this is old macOS browsers which cannot handle overlaps. But there are some others.

Best solution is to use a tool or a font editor to remove the overlaps.

**Comment by potatoShield** [comment]
> Overlaps are normal in variable font. So part of your conversion process must "remove overlaps" if you do not want them. You can use tools such as fonttools or foundrytools-cli to easily remove the overlaps.
> 
> Most modern browsers can handle overlaps even in static fonts. The most common offender in this is old macOS browsers which cannot handle overlaps. But there are some others.
> 
> Best solution is to use a tool or a font editor to remove the overlaps.

@herrstrietzel  found out this might be some compatibility issues. i opened this demo on macos browsers(chrome \ safari \ firefox), this problem still exists; but windows chrome / ios safari all renders as expectation
![image](https://github.com/user-attachments/assets/6865ddb9-65a0-4ecc-97c0-4d27a3631819)

the wired thing is that i use the original VF font, this problem does not exists, but after using opentype.js to minify font, this problem appears. i'll try to remove overlaps to see if this problem can be fixed. but now fonttools failed when i run removeOverlaps: https://github.com/fonttools/fonttools/issues/3629

**Comment by potatoShield** [comment]
> > Overlaps are normal in variable font. So part of your conversion process must "remove overlaps" if you do not want them. You can use tools such as fonttools or foundrytools-cli to easily remove the overlaps.
> > Most modern browsers can handle overlaps even in static fonts. The most common offender in this is old macOS browsers which cannot handle overlaps. But there are some others.
> > Best solution is to use a tool or a font editor to remove the overlaps.
> 
> @herrstrietzel found out this might be some compatibility issues. i opened this demo on macos browsers(chrome \ safari \ firefox), this problem still exists; but windows chrome / ios safari all renders as expectation ![image](https://private-user-images.githubusercontent.com/96233711/364330712-6865ddb9-65a0-4ecc-97c0-4d27a3631819.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDU3NzEsIm5iZiI6MTcyNTQ0NTQ3MSwicGF0aCI6Ii85NjIzMzcxMS8zNjQzMzA3MTItNjg2NWRkYjktNjVhMC00ZWNjLTk3YzAtNGQyN2EzNjMxODE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDEwMjQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmOTI1YWRhYzZlYzQ5Mzc3YWZhMTI2YWJmYjM0ODcwNGI0NzM1ZDk3YTY3NzRkNjIwZWI1YzcwMjFlNGJmNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D1pk2S6uh3NqOKEdJwtLTY85S1MJiFH3bUowbLI4b7c)
> 
> the wired thing is that i use the original VF font, this problem does not exists, but after using opentype.js to minify font, this problem appears. i'll try to remove overlaps to see if this problem can be fixed. but now fonttools failed when i run removeOverlaps: [fonttools/fonttools#3629](https://github.com/fonttools/fonttools/issues/3629)

fonttools is now unable to use removeOverlaps on a VF font, and i use removeOverlaps on the font file which has the wrong behavior, things turn out to be all good! so it's there any possibility for opentype.js to add a "removeOverlaps" feature after minify font files?

![image](https://github.com/user-attachments/assets/7421b533-3d7f-48a6-9cb2-6e8f492b3140)

**Comment by herrstrietzel** [comment]
@kenmcd: you're right variable fonts allow overlapping contours.  
Not sure but this may be an explanation for this issue:

while overlapping contours are valid in glyf and CFF2 they are not (at least not officially) supported in CFF (version 1).
When compiling a static new font via opentype.js you actually get a CFF (version1) .otf font output.  (See issue ["TTF gets converted to CFF")](https://github.com/opentypejs/opentype.js/issues/594) 

Speculative: Maybe some text rendering engines have updated their rendering logics to also accept overlapping contours in CFF(1) which is to my knowledge the only format opentype.js can currently export.  Safari/Webkit obviously didn't.

@potatoShield: so you probably don't need to flatten/merge overlapping contours as long as the converter supports a glyf/truetype or CFF2/otf output. The aforementioned fonttools are probably more suitable as this library is more focused on font manipulation whereas opentype.js is foremost a parser with SVG/canvas rendering capabilities but not intended as a universal converter.

I also updated the previous codepen example by adding the infamous CSS property `-webkit-text-stroke`  to illustrate the present overlapping contours.

![VF](https://github.com/user-attachments/assets/0b92ddca-d43a-4281-b99e-254cf9ba15d0)
