### ISSUE TITLE
Fonts crafted from scratch always result in "not a valid font file" on Windows

### ISSUE THREAD

**Issue by mattlag** [opentypejs/opentype.js#757]
I usually use v1.3.4, and assemble outlines into paths / glyphs / fonts and use opentype.js to export them to `otf` files. I started playing with the latest commit (which I will call the "July 30th" commit, because it is not a full release) to start seeing how SVG Table and Variable features are coming along. At some point I realized that no font assembled programmatically with the July 30th code results in a functional `otf` file.

## Expected Behavior

Fonts / Glyphs / Paths assembled programmatically should result in usable `otf` files.

## Current Behavior

I have a simple example in a [repo](https://github.com/mattlag/OTFJS-Export-Test/) - but it is basically the "Craft a font" example used in docs. If you try to do this with the July 30th code, it never (as far as I can tell) produces a functioning font file.

## Possible Solution

I tried using Fonttools TTX to look into both functional and non-functional `otf` files generated with v1.3.4 and the July 30th code. The main differences I saw in the new code is that it added an `ltag` table, and also added many `namerecord` entries in the `name` table with `platformID="0"`. I tried removing one and both of these new tables/entries and re-generating a font file with TTX, but the error seems to remain. So, I'm not sure what is causing Windows to not recognize the generated font files.

## Steps to Reproduce (for bugs)

The [repo src folder](https://github.com/mattlag/OTFJS-Export-Test/tree/main/src) is a basic bit of code that creates a good and bad otf file using two versions of opentype.js, you'll have to run it with something like `npx http-server` so the module imports work.

But a set of result files are already in the [repo result folder](https://github.com/mattlag/OTFJS-Export-Test/tree/main/result) in both otf and ttx format.

## Context

Overall, this is an investigation for Glyphr Studio - we leverage opentype.js to read and write font files. Opentype.js v1.3.4 is working great so far, but it would be awesome to integrate the new SVG Font and Variable Font features. Generating font objects from scratch then being able to export them to `otf` files is crucial.

## Your Environment

* Version used: Good export example, v1.3.4 / Bad export example, Latest commit from July 30th
* Font used: Generated from code
* Browser Name and version: Edge latest and Firefox latest
* Operating System and version (desktop or mobile): Windows 11
* Link to your project: https://github.com/mattlag/OTFJS-Export-Test/

**Comment by Connum** [comment]
Thanks for bringing this to our attention! Could you please try to find the last working commit by gradually stepping back?

**Comment by mattlag** [comment]
Oh, that's a good idea - I should have some time to try that today.

**Comment by mattlag** [comment]
Narrowed it down to Feb 4th, 2023

 - Build c331cca exports a valid font
 - The next build 4c06e44 fails to export a font at all
 - Build 858a5d2 and beyond exports a font that fails

![image](https://github.com/user-attachments/assets/a83da9e9-7328-4782-bf55-9984a788571c)

![image](https://github.com/user-attachments/assets/0ea72908-dc4d-4aba-97bb-8514bf51bd8b)

Here is the error from build 4c06e44 
![image](https://github.com/user-attachments/assets/00b04c97-9310-42ee-8de6-368bf3d9f43d)


Next up, looking into what changed...

**Comment by mattlag** [comment]
The specific error in commit 4c06e44 was fixed in commit 858a5d2... but 858a5d2 also introduces a bunch of new changes, so my hunch is the export issue is somewhere there.

**Comment by mattlag** [comment]
Doing a quick TTX diff between the working and non-working fonts, it seems like the working version has these `namerecord` entries, but the broken fonts do not:

```
<namerecord nameID="3" platformID="1" platEncID="0" langID="0x0" unicode="True">
```

and

```
<namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
```

**Comment by mattlag** [comment]
Confirmed, manually setting the windows uniqueID entry in the name table exports a valid font file:
```
font.names.windows.uniqueID = { en: ' :OTFJS-Export-Test-opentype_2024_07_30_UPDATE Regular' };
```

But still not sure why opentype is not creating the two missing `nameID="3"` `namerecord` entries...

**Comment by mattlag** [comment]
All right, this bit of code that was changed in is not doing what was intended, for two reasons:

1) the `for... in` loop is looping over the keys of the array, `0, 1, 2` as opposed to the values of the array (which looks like what was intended.
2) If an empty value is found, the unicode value is updated as opposed to whatever platform is currently being looped over.

So, this:

``` javascript
  for (const platform in ["unicode", "macintosh", "windows"]) {
    names[platform] = names[platform] || {};
    if (!names[platform].uniqueID) {
      names.unicode.uniqueID = { en: font.getEnglishName("manufacturer") + ":" + englishFullName };
    }
    if (!names[platform].postScriptName) {
      names.unicode.postScriptName = { en: postScriptName };
    }
  }
```
should become this:
``` javascript
  for (const platform in names) {
    names[platform] = names[platform] || {};
    if (!names[platform].uniqueID) {
      names[platform].uniqueID = { en: font.getEnglishName("manufacturer") + ":" + englishFullName };
    }
    if (!names[platform].postScriptName) {
      names[platform].postScriptName = { en: postScriptName };
    }
  }
```

I'll work on a PR for this!

**Comment by Connum** [comment]
Great work figuring this out!
