### ISSUE TITLE
Finding Middle Path of SVG Font Glyphs

### ISSUE THREAD

**Issue by Gautam2010** [opentypejs/opentype.js#769]
I came across [developer tool](http://metapolator.com/developer-tool/) 

that shows the middle path of an SVG font glyph being identified.

![image](https://github.com/user-attachments/assets/76657270-985a-4a38-9572-d55d63050bd5)

Is this can be achieved through opetype.js?

The technique demonstrated is very impressive and seems like it could have a wide range of uses. Any guidance or information on how to achieve this, would be greatly appreciated!

**Comment by herrstrietzel** [comment]
No there is no method in opentype.js to find a pen/stroke "skeleton" from an existing glyph outline. Afaik metapolator also doesn't include an automatic generator. The demo shows a font that was build with the custom pen structure (specifying pen angles and stroke widths). So you should rather ask the [metapolator devs/contributors](https://github.com/metapolator/metapolator) if anything like a generator is planned
