### ISSUE TITLE
Question: Get font-family and style / weight

### ISSUE THREAD

**Issue by quasado** [opentypejs/opentype.js#82]
hi,

Is there a reliable way to read the font-family, style (italic) and weight from any ttf/otf font?
I've found fontSubfamily and fontFamily on the name header table but is that reliable enough?

**Comment by mattsonar** [comment]
If there is another way please forgive me, but I found the fsSelection bitfield to be useful for style/weight as referenced in the opentype.js Font Inspector demo.  

This is the linked doc: https://www.microsoft.com/typography/OTSPEC/os2.htm#fss

You can access from a font like this:
var fsSelection = myFont.tables.os2.fsSelection;

Once that is done you can use bitwise operators to come up with any tests you need.  

You can probably just do pattern matches on font-family from the name table that you mentioned for the family, but the os2 table also contains another bitfield called sFamilyClass that may be of interest to you.

**Comment by Shugabuga** [comment]
This doesn't seem to work anymore. The `myFont` var doesn't have a `tables` property anymore.
